### ISSUE TITLE
missing type definition

### ISSUE THREAD

**Issue by heneault** [CastXML/CastXML#10]
Running the following test case:

    template<class _Ty1, class _Ty2>
    struct apair
    {	
      typedef _Ty1 first_type;
      typedef _Ty2 second_type;

      apair(const _Ty1& _Val1, const _Ty2& _Val2)
	    : first(_Val1), second(_Val2) {}
    
      first_type first;
      second_type second;
    };
  
    class start {
      apair<const aclass, double> p;
    };

The constructor for apair got generated like this:

    <Constructor id="_16" name="apair" context="_6" access="public" location="f1:20" file="f1" line="20" inline="1" attributes="__thiscall__">
      <Argument name="_Val1" type="_29" location="f1:20" file="f1" line="20"/>
      <Argument name="_Val2" type="_30" location="f1:20" file="f1" line="20"/>
    </Constructor>

Searching for the first type of `_Val1` (i.e. `_29`) give the following result:

    <ReferenceType id="_29" type="_27c"/>
    <CvQualifiedType id="_27c" type="_27" const="1"/>

But id `_27` is not defined anywhere in the XML.

**Comment by bradking** [comment]
Thanks.  Fixed by commit f0c00cb8bd3c5e6c38c6ee47370c15630e7446eb along with a test case.

**Comment by heneault** [comment]
fix doesn't compile on visual studio 2012.

7>Output.cxx(54): error C2864: 'ASTVisitorBase::DumpQual::IsConst' : only static const integral data members can be initialized within a class
7>Output.cxx(55): error C2864: 'ASTVisitorBase::DumpQual::IsVolatile' : only static const integral data members can be initialized within a class
7>Output.cxx(56): error C2864: 'ASTVisitorBase::DumpQual::IsRestrict' : only static const integral data members can be initialized within a class
7>Output.cxx(57): error C2071: 'ASTVisitorBase::DumpQual::operator bool' : illegal storage class
7>Output.cxx(87): error C2864: 'ASTVisitorBase::DumpId::Id' : only static const integral data members can be initialized within a class
7>Output.cxx(91): error C2071: 'ASTVisitorBase::DumpId::operator bool' : illegal storage class

**Comment by bradking** [comment]
Compilation fixed by commit e0e37477974e914cab60d9978bae5811d865cd62.
