### ISSUE TITLE
Test failures on Windows 10 with VS2017

### ISSUE THREAD

**Issue by todoooo** [CastXML/CastXML#111]
I am seeing 134 test failures on my Windows machine. It looks like none of the cmd.cc files are being generated. Possible the rest as well.

1>The following tests FAILED:
1> 50 - cmd.cc-gnu-src-c-E (Failed)
1> 51 - cmd.cc-gnu-src-cxx-E (Failed)
1> 52 - cmd.cc-gnu-src-cxx-cmd (Failed)
1> 53 - cmd.cc-gnu-tgt-amd64 (Failed)
1> 54 - cmd.cc-gnu-tgt-explicit (Failed)
1> 55 - cmd.cc-gnu-tgt-i386 (Failed)
1> 56 - cmd.cc-gnu-tgt-i386-opt-E (Failed)
1> 57 - cmd.cc-gnu-tgt-mingw (Failed)
1> 58 - cmd.cc-gnu-tgt-win (Failed)
1> 59 - cmd.cc-gnu-tgt-x86_64 (Failed)
1> 60 - cmd.cc-gnu-std-c++98 (Failed)
1> 61 - cmd.cc-gnu-std-c++11 (Failed)
1> 62 - cmd.cc-gnu-std-c++14 (Failed)
1> 63 - cmd.cc-gnu-std-gnu++98 (Failed)
1> 64 - cmd.cc-gnu-std-gnu++11 (Failed)
1> 65 - cmd.cc-gnu-std-gnu++14 (Failed)
1> 66 - cmd.cc-gnu-std-c++1z (Failed)
1> 67 - cmd.cc-gnu-std-c++17 (Failed)
1> 68 - cmd.cc-gnu-std-gnu++1z (Failed)
1> 69 - cmd.cc-gnu-std-gnu++17 (Failed)
1> 70 - cmd.cc-gnu-std-explicit (Failed)
1> 72 - cmd.cc-gnu-c-src-c-E (Failed)
1> 73 - cmd.cc-gnu-c-src-c-cmd (Failed)
1> 74 - cmd.cc-gnu-c-std-c89 (Failed)
1> 75 - cmd.cc-gnu-c-std-c99 (Failed)
1> 76 - cmd.cc-gnu-c-std-c11 (Failed)
1> 77 - cmd.cc-gnu-c-std-gnu89 (Failed)
1> 78 - cmd.cc-gnu-c-std-gnu99 (Failed)
1> 79 - cmd.cc-gnu-c-std-gnu11 (Failed)
1> 80 - cmd.cc-gnu-c-tgt-i386-opt-E (Failed)
1> 81 - cmd.cc-gnu-builtin-unique-object-representations (Failed)
1> 83 - cmd.cc-msvc-src-c-E (Failed)
1> 84 - cmd.cc-msvc-src-cxx-E (Failed)
1> 85 - cmd.cc-msvc-src-cxx-cmd (Failed)
1> 86 - cmd.cc-msvc-tgt-amd64 (Failed)
1> 87 - cmd.cc-msvc-tgt-explicit (Failed)
1> 88 - cmd.cc-msvc-tgt-i386 (Failed)
1> 89 - cmd.cc-msvc-tgt-win (Failed)
1> 90 - cmd.cc-msvc-tgt-x86_64 (Failed)
1> 91 - cmd.cc-msvc-std-c++98 (Failed)
1> 92 - cmd.cc-msvc-std-c++11 (Failed)
1> 93 - cmd.cc-msvc-std-c++14 (Failed)
1> 94 - cmd.cc-msvc-std-c++17 (Failed)
1> 95 - cmd.cc-msvc-std-explicit (Failed)
1> 96 - cmd.cc-msvc-builtin-1800-E (Failed)
1> 97 - cmd.cc-msvc-builtin-1900-E (Failed)
1> 98 - cmd.cc-msvc-builtin-1900 (Failed)
1> 100 - cmd.cc-msvc-c-src-c-E (Failed)
1> 101 - cmd.cc-msvc-c-src-c-cmd (Failed)
1> 102 - cmd.cc-msvc-c-std-c89 (Failed)
1> 2787 - gccxml.c89.GNU-float128 (Failed)
1> 2788 - castxml1.c89.GNU-float128 (Failed)
1> 2789 - gccxml.gnu89.GNU-float128 (Failed)
1> 2790 - castxml1.gnu89.GNU-float128 (Failed)
1> 2791 - gccxml.c99.GNU-float128 (Failed)
1> 2792 - castxml1.c99.GNU-float128 (Failed)
1> 2793 - gccxml.gnu99.GNU-float128 (Failed)
1> 2794 - castxml1.gnu99.GNU-float128 (Failed)
1> 2795 - gccxml.c11.GNU-float128 (Failed)
1> 2796 - castxml1.c11.GNU-float128 (Failed)
1> 2797 - gccxml.gnu11.GNU-float128 (Failed)
1> 2798 - castxml1.gnu11.GNU-float128 (Failed)
1> 2799 - gccxml.c89.GNU-float128-nostart (Failed)
1> 2800 - castxml1.c89.GNU-float128-nostart (Failed)
1> 2801 - gccxml.gnu89.GNU-float128-nostart (Failed)
1> 2802 - castxml1.gnu89.GNU-float128-nostart (Failed)
1> 2803 - gccxml.c99.GNU-float128-nostart (Failed)
1> 2804 - castxml1.c99.GNU-float128-nostart (Failed)
1> 2805 - gccxml.gnu99.GNU-float128-nostart (Failed)
1> 2806 - castxml1.gnu99.GNU-float128-nostart (Failed)
1> 2807 - gccxml.c11.GNU-float128-nostart (Failed)
1> 2808 - castxml1.c11.GNU-float128-nostart (Failed)
1> 2809 - gccxml.gnu11.GNU-float128-nostart (Failed)
1> 2810 - castxml1.gnu11.GNU-float128-nostart (Failed)
1> 2811 - gccxml.c++98.GNU-float128 (Failed)
1> 2812 - castxml1.c++98.GNU-float128 (Failed)
1> 2813 - gccxml.gnu++98.GNU-float128 (Failed)
1> 2814 - castxml1.gnu++98.GNU-float128 (Failed)
1> 2815 - gccxml.c++11.GNU-float128 (Failed)
1> 2816 - castxml1.c++11.GNU-float128 (Failed)
1> 2817 - gccxml.gnu++11.GNU-float128 (Failed)
1> 2818 - castxml1.gnu++11.GNU-float128 (Failed)
1> 2819 - gccxml.c++14.GNU-float128 (Failed)
1> 2820 - castxml1.c++14.GNU-float128 (Failed)
1> 2821 - gccxml.gnu++14.GNU-float128 (Failed)
1> 2822 - castxml1.gnu++14.GNU-float128 (Failed)
1> 2823 - gccxml.c++17.GNU-float128 (Failed)
1> 2824 - castxml1.c++17.GNU-float128 (Failed)
1> 2825 - gccxml.gnu++17.GNU-float128 (Failed)
1> 2826 - castxml1.gnu++17.GNU-float128 (Failed)
1> 2827 - gccxml.c++98.GNU-float128-nostart (Failed)
1> 2828 - castxml1.c++98.GNU-float128-nostart (Failed)
1> 2829 - gccxml.gnu++98.GNU-float128-nostart (Failed)
1> 2830 - castxml1.gnu++98.GNU-float128-nostart (Failed)
1> 2831 - gccxml.c++11.GNU-float128-nostart (Failed)
1> 2832 - castxml1.c++11.GNU-float128-nostart (Failed)
1> 2833 - gccxml.gnu++11.GNU-float128-nostart (Failed)
1> 2834 - castxml1.gnu++11.GNU-float128-nostart (Failed)
1> 2835 - gccxml.c++14.GNU-float128-nostart (Failed)
1> 2836 - castxml1.c++14.GNU-float128-nostart (Failed)
1> 2837 - gccxml.gnu++14.GNU-float128-nostart (Failed)
1> 2838 - castxml1.gnu++14.GNU-float128-nostart (Failed)
1> 2839 - gccxml.c++17.GNU-float128-nostart (Failed)
1> 2840 - castxml1.c++17.GNU-float128-nostart (Failed)
1> 2841 - gccxml.gnu++17.GNU-float128-nostart (Failed)
1> 2842 - castxml1.gnu++17.GNU-float128-nostart (Failed)
1> 2843 - gccxml.c89.GNU-va_arg_pack (Failed)
1> 2844 - castxml1.c89.GNU-va_arg_pack (Failed)
1> 2845 - gccxml.gnu89.GNU-va_arg_pack (Failed)
1> 2846 - castxml1.gnu89.GNU-va_arg_pack (Failed)
1> 2847 - gccxml.c99.GNU-va_arg_pack (Failed)
1> 2848 - castxml1.c99.GNU-va_arg_pack (Failed)
1> 2849 - gccxml.gnu99.GNU-va_arg_pack (Failed)
1> 2850 - castxml1.gnu99.GNU-va_arg_pack (Failed)
1> 2851 - gccxml.c11.GNU-va_arg_pack (Failed)
1> 2852 - castxml1.c11.GNU-va_arg_pack (Failed)
1> 2853 - gccxml.gnu11.GNU-va_arg_pack (Failed)
1> 2854 - castxml1.gnu11.GNU-va_arg_pack (Failed)
1> 2855 - gccxml.c++98.GNU-va_arg_pack (Failed)
1> 2856 - castxml1.c++98.GNU-va_arg_pack (Failed)
1> 2857 - gccxml.gnu++98.GNU-va_arg_pack (Failed)
1> 2858 - castxml1.gnu++98.GNU-va_arg_pack (Failed)
1> 2859 - gccxml.c++11.GNU-va_arg_pack (Failed)
1> 2860 - castxml1.c++11.GNU-va_arg_pack (Failed)
1> 2861 - gccxml.gnu++11.GNU-va_arg_pack (Failed)
1> 2862 - castxml1.gnu++11.GNU-va_arg_pack (Failed)
1> 2863 - gccxml.c++14.GNU-va_arg_pack (Failed)
1> 2864 - castxml1.c++14.GNU-va_arg_pack (Failed)
1> 2865 - gccxml.gnu++14.GNU-va_arg_pack (Failed)
1> 2866 - castxml1.gnu++14.GNU-va_arg_pack (Failed)
1> 2867 - gccxml.c++17.GNU-va_arg_pack (Failed)
1> 2868 - castxml1.c++17.GNU-va_arg_pack (Failed)
1> 2869 - gccxml.gnu++17.GNU-va_arg_pack (Failed)
1> 2870 - castxml1.gnu++17.GNU-va_arg_pack (Failed)

**Comment by bradking** [comment]
Try running just one test with verbose output e.g. `ctest -R cmd.cc-gnu-src-c-E -V`.

**Comment by bradking** [comment]
FWIW, these pass for me with VS 2017 on Windows.

**Comment by todoooo** [comment]
D:\3RD_PARTY\Build-castXML_32\test>ctest -R cmd.cc-gnu-src-c-E -V -C Debug

UpdateCTestConfiguration  from :D:/3RD_PARTY/Build-castXML_32/test/DartConfiguration.tcl
UpdateCTestConfiguration  from :D:/3RD_PARTY/Build-castXML_32/test/DartConfiguration.tcl
Test project D:/3RD_PARTY/Build-castXML_32/test
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 50
    Start 50: cmd.cc-gnu-src-c-E

50: Test command: "C:\Program Files\CMake\bin\cmake.exe" "-Dcommand:STRING=D:/3RD_PARTY/Build-castXML_32/bin/Debug/castxml.exe;--castxml-cc-gnu;D:/3RD_PARTY/Build-castXML_32/test/Debug/cc-gnu.exe;D:/3RD_PARTY/CastXML/test/input/empty.c;-E;-dM" "-Dexpect=cmd.cc-gnu-src-c-E" "-P" "D:/3RD_PARTY/CastXML/test/run.cmake"
50: Test timeout computed to be: 9.99988e+006
50: CMake Error at D:/3RD_PARTY/CastXML/test/run.cmake:110 (message):
50:   stderr does not match that expected.
50:
50:   Command was:
50:
50:    command> "D:/3RD_PARTY/Build-castXML_32/bin/Debug/castxml.exe" "--castxml-cc-gnu" "D:/3RD_PARTY/Build-castXML_32/test/Debug/cc-gnu.exe" "D:/3RD_PARTY/CastXML/test/input/empty.c" "-E" "-dM"
50:
50:   Expected stderr to match:
50:
50:    expect-stderr> ^error: invalid argument '-std=gnu\+\+98' not allowed with 'C(/ObjC)?'$
50:
50:   Actual result:
50:
50:    actual-result> 1
50:
50:   Actual stdout:
50:
50:    actual-stdout>
50:
50:   Actual stderr:
50:
50:    actual-stderr> error: '--castxml-cc-gnu' compiler command failed:
50:    actual-stderr>
50:    actual-stderr>  'D:/3RD_PARTY/Build-castXML_32/test/Debug/cc-gnu.exe' '-E' '-dM' '-v' 'D:/3RD_PARTY/CastXML/share/castxml/empty.cpp'
50:    actual-stderr> program not executable
50:
50:
50:
1/1 Test #50: cmd.cc-gnu-src-c-E ...............***Failed    0.28 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.69 sec

The following tests FAILED:
         50 - cmd.cc-gnu-src-c-E (Failed)
Errors while running CTest

**Comment by bradking** [comment]
Does `D:/3RD_PARTY/Build-castXML_32/test/Debug/cc-gnu.exe` exist?  Can you run it by hand?

**Comment by todoooo** [comment]
All passed. See previous comment.
