### ISSUE TITLE
error castxml

### ISSUE THREAD

**Issue by adrianurcahyo** [CastXML/CastXML#112]
i have an error while build castxml and the command show like this:

>> Building castxml - 
    > mkdir -p /home/baba/dce/build/bin
 mkdir /home/baba/dce/source/castxml/objdir dir=/home/baba/dce/source/castxml
mkdir: cannot create directory ‘/home/baba/dce/source/castxml/objdir’: File exists
 cmake /home/baba/dce/source/castxml -DCMAKE_INSTALL_PREFIX:PATH=/home/baba/dce/build dir=/home/baba/dce/source/castxml/objdir
CMake Error at CMakeLists.txt:95 (find_package):
  By not providing "FindLLVM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LLVM", but
  CMake did not find one.

  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/baba/dce/source/castxml/objdir/CMakeFiles/CMakeOutput.log".
()
 >> Building castxml - Problem
   > Subprocess failed with error 1: ['cmake', '/home/baba/dce/source/castxml', '-DCMAKE_INSTALL_PREFIX:PATH=/home/baba/dce/build']

how to fix it??

**Comment by bradking** [comment]
See the readme's [build instructions](https://github.com/CastXML/CastXML#build).  You need to build LLVM/Clang first, or install the SDK from a distro package manager.
