### ISSUE TITLE
error: no template named 'remove_reference

### ISSUE THREAD

**Issue by rk540** [CastXML/CastXML#113]
I am trying to use castxml with py++.  It runs the following command and the first errors are given below.

This is on linux centos 7.

Any help will be much appreciated.

"/srllc/tp/castXML/v6.0.0/bin/castxml"  -fpermissive   -I"." -I"/opt/gcc-7.3.0/include/c++/7.3.0/tr1" -I"./" -I"/srllc/software/Utilities/v4.0.0/include/" -I"../" -I"/srllc/software/Utilities/v4.0.0/include/Utilities" -I"/srllc/software/logging/v5.0.1/include" -c -x c++ --castxml-cc-gnu  /opt/gcc-7.3.0/bin/c++ --castxml-gccxml -o /tmp/tmppvrz953i.xml Contracts/VanillaOptionContract.h
In file included from Contracts/VanillaOptionContract.h:11:
In file included from ./Interfaces/IContract.h:11:
In file included from /srllc/software/Utilities/v4.0.0/include/Utilities/Factory/GenericFactory.h:10:
In file included from /srllc/software/logging/v5.0.1/include/logging/loggingmacros.h:4:
In file included from /srllc/software/logging/v5.0.1/include/logging/logging.h:10:
In file included from /opt/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/string:40:
In file included from /opt/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/char_traits.h:39:
In file included from /opt/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_algobase.h:64:
In file included from /opt/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/stl_pair.h:59:
/opt/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/bits/move.h:73:22: error: no template named 'remove_reference'
      in namespace 'std'; did you mean 'tr1::remove_reference'?
    forward(typename std::remove_reference<_Tp>::type& __t) noexcept
                     ^~~~~
/opt/gcc-7.3.0/include/c++/7.3.0/tr1/type_traits:643:12: note: 'tr1:

**Comment by bradking** [comment]
Does running the normal compiler in the same way work?

```console
$ /opt/gcc-7.3.0/bin/c++ -fpermissive -I"." -I"/opt/gcc-7.3.0/include/c++/7.3.0/tr1" -I"./" -I"/srllc/software/Utilities/v4.0.0/include/" -I"../" -I"/srllc/software/Utilities/v4.0.0/include/Utilities" -I"/srllc/software/logging/v5.0.1/include" -c -x c++ Contracts/VanillaOptionContract.h
```

I don't think the `/opt/gcc-7.3.0/include/c++/7.3.0/tr1` directory is supposed to be explicitly passed as an include path.
