### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by ilovezfs** [CastXML/CastXML#114]
As far as I can tell, the various package managers are just inventing release numbers out of thin air:
https://repology.org/metapackage/castxml/versions

Can you please add actual tags on GitHub so that we can automate the upgrades? Thanks!

**Comment by bradking** [comment]
Yes, lacking real releases the packaged versions are all based on the date of the commit used.  It's not quite out of thin air but it's not as good as real releases would be.

This is already requested in #82 so I'll close this as a duplicate.
