### ISSUE TITLE
Does CastXML works with MSBuild?

### ISSUE THREAD

**Issue by littlesome** [CastXML/CastXML#116]
I have a Visual Studio C++ project, and I try to generate xml with castxml with no success, here is the steps:
```
msbuild.exe <path-to-vcxproj> /p:CLToolExe=castxml.bat /p:CLToolPath=<path-to-castxml-dir>
```

in castxml.bat, I try to foward commands to castxml.exe

```
castxml.exe --castxml-gccxml --castxml-cc-msvc ( "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" %* )
```

I got some errors: 
cl : error D8036: “/FoNUL”

Any suggestions?

**Comment by todoooo** [comment]
Yes it does, but you first need to build/install CLang/llvm; hence the
error about the missing CL tool path.

I believe the readme gives details about seeing this up.

Todd

**Comment by bradking** [comment]
> `/p:CLToolExe=castxml.bat`

That isn't expected to work.

Instead you should run castxml as a custom build script.  When the script runs `cl` should be in the `PATH` so you can use just `castxml.exe --castxml-gccxml --castxml-cc-msvc cl ...`.

**Comment by littlesome** [comment]
OK, thanks :)
