### ISSUE TITLE
Instrumenting source code for CastXML

### ISSUE THREAD

**Issue by decimad** [CastXML/CastXML#119]
Hey there,
currently I'm taking CastXML output and a handcrafted list file with a list of functions to generate stubs and mocks. This works nicely, a great thank your this ;)
However I was wondering if there is a "portable" way, or at least one that works nicely with gcc and clang, to add instrumentation information transparently for code generation, that ends up as additional information in the generated XML. Specifically, I would like to mark functions/symbols directly in source for stub generation.

**Comment by bradking** [comment]
We support outputting annotation attributes:

```c++
__attribute__((annotate("my annotation"))) void myfunction(int);
```

The "my annotation" will be included in the xml output.

In practice you could add them through a macro and define the macro conditionally based on when castxml is processing the translation unit.

**Comment by decimad** [comment]
That's great news, thank you!
