### ISSUE TITLE
"Unable to locate resources for <...>\castxml.exe"

### ISSUE THREAD

**Issue by vanxining** [CastXML/CastXML#12]
I built CastXML using Visual Studio 2013. But I encoutered a problem launching the output executable.
The error message is "Unable to locate resources for <...>\castxml.exe".
It seems that the cause is the folder named "share/castxml/clang" is missing.

**Comment by bradking** [comment]
We build CastXML with VS 2013 regularly and do not see this.

* What version (commit sha1) did you build?
* What version of LLVM/Clang did you build against?
* What CMake version did you use?
* What CMake generator did you use?  For x86 or x64?

From where did you run the executable?  Directly from the build tree or install tree?

**Comment by vanxining** [comment]
I found the file "castxmlClangResourceDir.txt" located in "build\CMakeFiles" was empty, so I added to it the path of Clang's lib dir (in my case was "<LLVM>\build\Release\lib\clang\3.6.0"). Finally CastXML worked.

What version (commit sha1) did you build?
-- The latest commit 0a10370aed
What version of LLVM/Clang did you build against?
-- 3.6.0
What CMake version did you use?
What CMake generator did you use? For x86 or x64?
-- CMake version 3.2.2 x86
From where did you run the executable? Directly from the build tree or install tree?
-- I ran it from the install tree, but it failed with the error message "Unable to locate resources for <...>\castxml.exe". With "castxmlClangResourceDir.txt" modified, I ran the executable from the build tree, and got the correct result successfully.

**Comment by bradking** [comment]
Thanks.  All of the problems running in both the build and install trees come from `CLANG_RESOURCE_DIR` not being set in the CMake cache in the build tree.   There is code [here](https://github.com/CastXML/CastXML/blob/0a10370aedd3cc08ebe2a8c0909406859058e146/CMakeLists.txt#L62-L71) that is supposed to detect this location automatically if the user does not set the cache entry explicitly.  Please try to figure out why that setting is not detected for you.

**Comment by vanxining** [comment]
Thanks!
I will try it and post feedback here.

**Comment by bradking** [comment]
Meanwhile I pushed commit fe633c27027856a7ce4b344f8fc1f2f1da8a917c to fail at CMake time if the Clang resources cannot be found.  It also prints out the places it tried looking which might help you debug it.

**Comment by vanxining** [comment]
I tried the latest version, and got a CMake configure error message:

> CMake Error at CMakeLists.txt:77 (message):
>   Could not find CLANG_RESOURCE_DIR.  Tried:
> 
>     D:/Work/CppLibs/LLVM/build/$(Configuration)/lib/clang/3.6.0
> 
>   Please set CLANG_RESOURCE_DIR to the Clang SDK directory containing 
> "include/stddef.h", typically of the form "<prefix>/lib/clang/3.6.0".

This path is the value of `${LLVM_LIBRARY_DIRS}` which is defined in "LLVM\build\share\llvm\cmake\LLVMConfig.cmake" line 96:

    set(LLVM_LIBRARY_DIRS "D:/Work/CppLibs/LLVM/build/$(Configuration)/lib")

Though I can't figure out why this happens, I think the error message is a useful guide to make a successful build after setting `CLANG_RESOURCE_DIR` to a proper directory manually in CMake GUI. (I don't know much about CMake.)

Thanks!

**Comment by vanxining** [comment]
I finally figure out the real cause.
I compiled CastXML on the build tree of LLVM/Clang SDK directly. Actually, the install tree must be used.

Please forgive me for such a stupid mistake. Thanks for your time. :+1: 

CastXML is really useful. Many thanks!

**Comment by bradking** [comment]
Thanks.  I pushed commit 40aed5c681c2355614d00b77f9eb372a77fa6a30 to reject attempts to use a LLVM/Clang build tree up front.

**Comment by suedlaender83** [comment]
@vanxining @bradking This is an old thread but i will give it a try. Maybe i get an answer. I'm new to Castxml and I'm trying to build it with a preinstalled Clang. I'm having the same issues you described here. My question is how to find the "install tree" and how to differentiate "install tree" from a "build tree"? I suspect that this would also resolve my issue once i figure out where i can find the "install tree". Many thanks in advance.

**Comment by bradking** [comment]
@suedlaender83 the discussion of "build tree" versus "install tree" above is about the build of LLVM/Clang.  If you're using a distro-installed package the "install tree" is what comes with the package.  Be sure to install the Clang library **development** package, such as `libclang-11-dev` (the name may depend on the distro and the version of clang).

**Comment by suedlaender83** [comment]
Thanks a lot for the explanation @bradking
