### ISSUE TITLE
error C2039: “GetArgumentVector”: is not “llvm::sys::Process” member

### ISSUE THREAD

**Issue by zjd1988** [CastXML/CastXML#120]
I have install Clang/LLVM SDK（clang version 7.0.0 (trunk 337893)），and generate castxml.sln with Cmake。but when i build the castxml.sln，get “error C2039: “GetArgumentVector”: is not “llvm::sys::Process” member” ，how can i fix it？

**Comment by zjd1988** [comment]
i have check the svn log,and find this
"""
Revision: 330216
Author: ruiu
Date: 2018年4月18日 5:09:16
Message:
**Rename sys::Process::GetArgumentVector -> sys::windows::GetCommandLineArguments**

GetArgumentVector (or GetCommandLineArguments) is very Windows-specific.
I think it doesn't make much sense to provide that function from sys::Process.

I also made a change so that the function takes a BumpPtrAllocator
instead of a SpecificBumpPtrAllocator. The latter is the class to call
dtors, but since char * is trivially destructible, we should use the
former class.

Differential Revision: https://reviews.llvm.org/D45641
----
Modified : /llvm/trunk/include/llvm/Support/InitLLVM.h
Modified : /llvm/trunk/include/llvm/Support/Process.h
Modified : /llvm/trunk/lib/Support/InitLLVM.cpp
Modified : /llvm/trunk/lib/Support/Unix/Process.inc
Modified : /llvm/trunk/lib/Support/Windows/Process.inc
Modified : /llvm/trunk/lib/Support/Windows/WindowsSupport.h
"""

Hoping add some statements in readme.md

**Comment by zjd1988** [comment]
@bradking ，OK ，thank you！

**Comment by bradking** [comment]
#122 fixes this compiler error on LLVM/Clang trunk as of the SVN version the PR newly documents.
