### ISSUE TITLE
error: invalid argument '-std=c++14' not allowed with 'C'

### ISSUE THREAD

**Issue by zjd1988** [CastXML/CastXML#121]
I used vs2017 , when i run the command 
**"castxml.exe test.i --castxml-cc-msvc "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64\cl.exe" -o test.xml"**
(test.i is generated from test.cpp---pre-compiled  intermediate file)

and get 
**error: invalid argument '-std=c++14' not allowed with 'C'**

How can i fix this?

**Comment by bradking** [comment]
Clang (and therefore CastXML) doesn't recognize the `.i` extension as any particular language so it defaults to `C`.  Use `castxml -x c++ test.i ...` to specify that the source file is in C++.

**Comment by zjd1988** [comment]
thank you，it works ！

**Comment by zjd1988** [comment]
thank you，it works ！@bradking
