### ISSUE TITLE
excute castxml with cc_option error (vs2013 )

### ISSUE THREAD

**Issue by zjd1988** [CastXML/CastXML#123]
I have a vs 2012 proj,and I want to use castxml to get the xml,
when i ran cmd below

castxml.exe test.cpp --castxml-cc-msvc "(" "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe" /Yu"stdafx.h" /GS /analyze- /W3 /Zc:wchar_t  /I".\include" /I"..\..\opencv\include" /I"..\..\opencv\include\opencv" /I"..\..\opencv\include\opencv2" /I"..\..\openni2\include" /ZI /Gm /Od /sdl /Fd".\Debug\vc120.pdb" /fp:precise /D "WIN32" /D "_DEBUG" /D "_CONSOLE" /D "_LIB" /D "_XKEYCHECK_H" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /Oy- /MDd /Fa".\Debug\" /EHsc /nologo /Fo".\Debug\" /Fp".\Debug\optimseTest.pch"  ")" --castxml-gccxml -o test.xml

I get errors as follows:

error: '--castxml-cc-msvc' compiler command failed:

 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe' '/Yustdafx.h' '/GS' '/analyze-' '/W3' '/Zc:wchar_t' '/IC:\CEVA-ToolBox\V16\XM4\CEVA-XM4\Vec-C\xm4\include\include' '/I.\include' '/I..\..\opencv\include' '/I..\..\opencv\include\opencv' '/I..\..\opencv\include\opencv2' '/I..\..\openni2\include' '/ZI' '/Gm' '/Od' '/sdl' '/Fd.\Debug\vc120.pdb' '/fp:precise' '/D' 'WIN32' '/D' '_DEBUG' '/D' '_CONSOLE' '/D' '_LIB' '/D' '_XKEYCHECK_H' '/D' '_UNICODE' '/D' 'UNICODE' '/errorReport:prompt' '/WX-' '/Zc:forScope' '/RTC1' '/Gd' '/Oy-' '/MDd' '/Fa.\Debug" /EHsc /nologo /Fo.\Debug"' '/Fp.\Debug\optimseTest.pch' '-c' '-FoNUL' 'C:\Program Files\CastXML/share/castxml/detect_vs.cpp'
detect_vs.cpp
c:\program files\castxml\share\castxml\detect_vs.cpp(153) : fatal error C1010: Encountered unexpected end of file when looking for precompiled header. Did you forget to add “#include "stdafx.h"”?

**Comment by bradking** [comment]
Don't pass the `/Yu...` flag to `--castxml-cc-msvc`.  That option is meant to be given a generic compiler command line that can compile any source.

CastXML runs the supplied compiler command on an internal `detect_vs.cpp` source to detect information about how the compiler operates so that our internal Clang can be configured in a compatible way.  That source doesn't `#include "stdafx.h"` and doesn't know about precompiled headers.
