### ISSUE TITLE
Test failures with VS2017

### ISSUE THREAD

**Issue by todoooo** [CastXML/CastXML#129]
Hi Brad

I'm seeing the following test failures with the latest source from master compiled with LLVM6

1>99% tests passed, 3 tests failed out of 2871
1>
1>Total Test time (real) = 411.30 sec
1>
1>The following tests FAILED:
1>	  1 - cmd.help1 (Failed)
1>	  2 - cmd.help2 (Failed)
1>	 81 - cmd.cc-gnu-builtin-unique-object-representations (Failed)

**Comment by bradking** [comment]
Please run `ctest -C Release -R cmd.help1 -V` in the build tree and post the output here (replace `Release` with whatever configuration you built).

**Comment by todoooo** [comment]
@bradking I'm using a debug build, so the /release folder does not exist.
Here's the output.

Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: cmd.help1

1: Test command: "C:\Program Files\CMake\bin\cmake.exe" "-Dcommand:STRING=D:/3RD_PARTY/Build-castXML_32/bin/Release/castxml.exe;-help" "-Dexpect=cmd.help1" "-P" "D:/3RD_PARTY/CastXML/test/run.cmake"
1: Test timeout computed to be: 1500
1: CMake Error at D:/3RD_PARTY/CastXML/test/run.cmake:110 (message):
1:   result does not match that expected.
1:
1:   stdout does not match that expected.
1:
1:   Command was:
1:
1:    command> "D:/3RD_PARTY/Build-castXML_32/bin/Release/castxml.exe" "-help"
1:
1:   Expected result to match:
1:
1:    expect-result> 0
1:
1:   Expected stdout to match:
1:
1:    expect-stdout> ^Usage: castxml .*
1:    expect-stdout>
1:    expect-stdout> Help for the internal Clang compiler appears below.
1:    expect-stdout>
1:    expect-stdout> ---------------------------------------------------------------
1:    expect-stdout>
1:    expect-stdout> OVERVIEW: clang LLVM compiler
1:
1:   Actual result:
1:
1:    actual-result> The system cannot find the file specified
1:
1:   Actual stdout:
1:
1:    actual-stdout>
1:
1:   Actual stderr:
1:
1:    actual-stderr>
1:
1:
1:
1/1 Test #1: cmd.help1 ........................***Failed    0.11 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.68 sec

The following tests FAILED:
          1 - cmd.help1 (Failed)
Errors while running CTest

**Comment by todoooo** [comment]
> Take a look at src/RunClang.cxx where it defines __has_unique_object_representations. Is that code path taken when you compile?

No.

I built LLVM months ago and kept the install folder, but not the build folder, so I can't remember whether I used the master branch or the tagged release. The clang version is shown as 6.0.0, but the header files in the /include folder contain no definition for __has_unique_object_representations.

**Comment by bradking** [comment]
@todoooo that is likely a development version from after 5.x but before the 6.x release.  Please use a current 6.0 release.

**Comment by todoooo** [comment]
I have built against LLVM 7 now and all tests pass.
