### ISSUE TITLE
LLVMversion.lib required for "Win32" build not found in LLVM build

### ISSUE THREAD

**Issue by risa2000** [CastXML/CastXML#133]
I had LLVM 7.0.1 project built using following `cmake` arguments:
```
cmake -G "Visual Studio 15 2017" -A x64 -Thost=x64 -DCMAKE_INSTALL_PREFIX=D:\Dev\LLVM -DLLVM_ENABLE_PROJECTS=clang;libcxx;libcxxabi;compiler-rt;lld;polly;debuginfo-tests ..
cmake --build . --target INSTALL --config Release
```
then was trying to build `CastXML` with this:
```
cmake -DLLVM_DIR=D:\Dev\LLVM\lib\cmake\llvm -G "Visual Studio 15 2017" -A x64 -Thost=x64 -DCMAKE_INSTALL_PREFIX=D:\Dev\CastXML -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target INSTALL --config Release
```
The first `cmake` run through but the build itself always failed with an error from the linker that it could not locate `LLVMversion.lib`. I have searched the LLVM build for any hint what might generate this library, but was not successful (this does not mean that there are no means to do it, just I did not find them).

Then looking at [src/CMakeList.txt](https://github.com/CastXML/CastXML/blob/master/src/CMakeLists.txt) I noticed this:
```
if(WIN32)
  list(APPEND llvm_libs version.lib)
endif()
```
Commenting the block out and regenerating `cmake` files makes the build and install pass.
So I wonder, is this really relevant? If yes, I guess some other precision is needed since on "my" `Win32` the library does not exist and is not needed either.

**Comment by bradking** [comment]
Cc: @dankm

It looks like this was broken by #132.  That PR changed the meaning of `llvm_libs` from "list of library names" to "list of LLVM components", and the MS `version.lib` library is not a LLVM component.

**Comment by dankm** [comment]
@bradking Yup. My bad, this is what I get for not testing Windows :/
