### ISSUE TITLE
Won't build with `ninja: build stopped: subcommand failed.`

### ISSUE THREAD

**Issue by TheChymera** [CastXML/CastXML#137]
with 

```
cmake -C /var/tmp/portage/dev-cpp/castxml-0.0.0_pre8/work/castxml-0.0.0_pre8_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-cpp/castxml-0.0.0_pre8/work/castxml-0.0.0_pre8_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-cpp/castxml-0.0.0_pre8/work/CastXML-0.0.0_pre8
```

I get the following [build.log](https://github.com/CastXML/CastXML/files/3001187/build.log).

On a system with:

* `=dev-libs/glib-2.58.3`
* `=dev-libs/libxml2-2.9.9-r1`
* `=sys-devel/llvm-8.0.0`
* `=sys-devel/clang-8..0.0`

**Comment by bradking** [comment]
What CastXML source version (git commit) is that package trying to compile?

**Comment by TheChymera** [comment]
I do not know what commit exactly this corresponds to, but the archive URL is: https://github.com/gerddie/CastXML/archive/0.0.0_pre8.tar.gz 

Should I try with the master HEAD?

**Comment by bradking** [comment]
Yes, please try `master`.  The diffs between that tarball and the current `master` include code like `#if LLVM_VERSION_MAJOR >= 7`, and you're building against LLVM 8.

**Comment by TheChymera** [comment]
@bradking thank you, the current HEAD compiles. Could you tell me how to run the tests? Also, would it be possible for you to release an archive?

**Comment by bradking** [comment]
Great.  Use `ctest -j 20` to run the tests.

See #82 about releases.
