### ISSUE TITLE
Assertion DD && "queried property of class with no definition"

### ISSUE THREAD

**Issue by manuka89** [CastXML/CastXML#143]
Hi,

Upon trying to generate the .xml file I have the following assertion:

castxml: /usr/local/include/clang/AST/DeclCXX.h:669: clang::CXXRecordDecl::DefinitionData& clang::CXXRecordDecl::data() const: Assertion `DD && "queried property of class with no definition"' failed.

After having checked it with GDB, the DD pointer is 0. I'm using  LLVM 8.0 and Clang 8.0 compiled with GCC 7.3 on Centos 7.6.

**Comment by bradking** [comment]
Please try to narrow down your source code to a small example that we can use to reproduce this.

**Comment by manuka89** [comment]
I will try to narrow the source code although it will be difficult. I gave an .hpp file to castXML which is a part of a huge project with a lot of includes so I have no clue which file causes the issue.  

It gives me a stack dump I'm not sure it is helpful or not. Should I try the castxml-start option for narrowing?

**Comment by manuka89** [comment]
It looks like it is not related to castXML but to clang as the assertion happens in clang...

**Comment by bradking** [comment]
CastXML makes deep use of Clang's APIs and could be violating something that triggers the assertion.

In order to narrow down the example, first use `castxml -E` to generate preprocessed output and save that to a file.  Then run `castxml` to generate XML from that intermediate file.  Then you should be able to start removing code from the end of the file and simplifying it incrementally.

If the content is not proprietary then you're welcome to just attach the entire preprocessed output file here instead.

**Comment by manuka89** [comment]
Thanks ! And what is the option to give the generated file to castXML?

**Comment by bradking** [comment]
Just name the preprocessed output file as the source to castxml instead of the `.hpp` file.

**Comment by manuka89** [comment]
I found the issue which was related to one of our header file which could not be parsed by Clang. After having corrected it I managed to generate the XML file. As it was not related to castXML I close the issue.

**Comment by manuka89** [comment]
Could you please tell me if internally castXML uses CLANG compiler what does it do the option --castxml-cc-<id> <cc> ?

**Comment by bradking** [comment]
The `castxml` binary does not actually invoke the `clang` compiler front-end internally.  Instead it links to the same Clang internal libraries that the `clang` compiler front-end does.  It is essentially a new front-end tool.  `castxml` processes the `--castxml-*` options and then passes the rest to Clang's internal APIs.

**Comment by manuka89** [comment]
Hi,

I've recently become familiar with the Clang Libtooling and the AST parsing process. There are lot of examples which uses the ASTConsumer HandleTranslationUnit function as you do. But in these example a visitor class is used to traverse all the declaration in the HandleTranslationUnit function. After having looked at the source code you are doing it another way. Could you please tell me what is the difference. 

Thank you in advance.

**Comment by bradking** [comment]
CastXML is using a visitor.  See `src/Output.cxx`'s `ASTVisitor` class.  Note that its base class uses `#include "clang/AST/DeclNodes.inc"` and `#include "clang/AST/TypeNodes.def"` to populate methods for all AST types.

**Comment by manuka89** [comment]
Thank you for your response and your explication.

I checked the generated functions with the macros you mentioned. So as I understood it is the outputXML function which calls your
visitor's HandleTranslationUnit function. In which you define an entry point (either the full AST or just the user defined starting points)
and then declarations are added to a queue which is processed by the processQueue function where the OutputXXX functions dispatches the calls.

As I see the nodes, added by the AddDumNodeImp function, are added one after the other to loop through all the AST recursively so you do not use the 
visitXXX methods of the visitor. Am I correct? So for instance, if my entry point was a translation unit the processQueue function will dispatch me to the OutputTranslationUnitDecl function which, by calling the PrintMembersAttribute, will print the translation unit related info to the XML and add further DumpNodes to the Queue.

So the clang::Sema structure is only for instantiating implicit declarations isn't it?

**Comment by bradking** [comment]
Your analysis of `Output.cxx` is correct.  `clang::Sema` is Clang's primary semantic model of the C++ translation unit.  `RunClang.cxx` hooks into it to ensure needed implicit instantiations are available in the AST.

**Comment by manuka89** [comment]
Thank you very much.

Just one more question :) As I checked the OutputEnumDecl function, the underlying type of the enum is not dumped to the XML. So currently it is not available in castXML? (It can be retrieved by the function getIntegerType() in clang as I see)

**Comment by bradking** [comment]
Ah, `OutputEnumDecl` is simply missing the underlying type information.  The output format comes from gccxml which was C++98-only where the underlying type was not specified.

**Comment by manuka89** [comment]
Okay, in that case I may do a PR. I guesss, a PrintTypeAttribute call should be added to the function. As the type contains the size and the alignment it is a redundant information but it may should be kept to keep compatibility with older versions or with pygccxml.
