### ISSUE TITLE
XML for Clang

### ISSUE THREAD

**Issue by todoooo** [CastXML/CastXML#144]
Hi

I'm wondering about the command line option `--castxml-cc-`

There are 4 possibilities gnu, gnu-c, msvc and msvc-c. Looking at the code these setup different compiler definitions and includes for either gnu or msvc. What if the target compiler is actually CLang? Shouldn't there be another option?

**Comment by bradking** [comment]
Those options are documented in the manual as having the form `--castxml-cc-<id>` where:

> The `<id>` names a reference compiler with which the given command is compatible.

The `clang` and `clang++` tools have commands-lines compatible with GNU tools, so use the `gnu-c` or `gnu` variants for them.

**Comment by todoooo** [comment]
Ah ok. Thanks.
