### ISSUE TITLE
MinGW: error including mutex header

### ISSUE THREAD

**Issue by flip111** [CastXML/CastXML#154]
I downloaded the CastXML binary `https://data.kitware.com/api/v1/file/5d41e403877dfcc9023cdeb7/download?contentDisposition=inline` created `July 31, 2019 at 20:54:59`.

I use the following source code: https://github.com/google/re2

I issue this command: `castxml -o re2.xml -x c++ -D"__MSVCRT__" -working-directory"C:\Users\flip111\re2" -I"C:\MinGW\lib\gcc\mingw32\8.2.0\include\c++\mingw32" -I"C:\MinGW\lib\gcc\mingw32\8.2.0\include\c++" -I"C:\MinGW\include" re2/re2.h`

I get the following error:
```
C:\Users\flip111\re2\re2/re2.h:199:10: fatal error: 're2/stringpiece.h' file not found
#include "re2/stringpiece.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

This error comes from the following line: https://github.com/google/re2/blob/master/re2/re2.h#L199

I don't expect this to be a problem in the source code because `re2` is being used by many people.

This was tried in the `git bash` terminal in windows. I also briefly tried it in `cmd.exe`:
```
C:\Users\flip111>castxml -o re2.xml -x c++ -D"__MSVCRT__" -working-directory"C:\Users\flip111\re2" -I"C:\MinGW\lib\gcc\mingw32\8.2.0\include\c++\mingw32" -I"C:\MinGW\lib\gcc\mingw32\8.2.0\include\c++" -I"C:\MinGW\include" re2\re2.h
C:\Users\flip111\re2\re2\re2.h:199:10: fatal error: 're2/stringpiece.h' file not found
#include "re2/stringpiece.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by bradking** [comment]
When a source file contains `#include "..."`, the included file is expected to exist either next to that file or in the `-I` search path.  In your case the source file is `re2/re2.h` double quote includes start under `re2/`.  It looks like the re2 source assumes that `-I...` will be used to specify the directory.

Also you shouldn't have to specify the mingw implicit include directories explicitly.  Use `--castxml-cc-gnu g++` to tell castxml to compute that information automatically from the `g++` compiler.

**Comment by flip111** [comment]
Hi @bradking thank you for your reply. This already helped a lot. From the directory `C:\Users\flip111\re2\` i now issue the following command `castxml -o re2.xml -x c++ --castxml-cc-gnu g++ -std=gnu++11 -I"." re2/re2.h`. I get a bunch of errors and warnings. The notable error is:

```
re2/re2.h:763:16: error: no type named 'once_flag' in namespace 'std'
  mutable std::once_flag rprog_once_;
          ~~~~~^
```

After searching for `once_flag` i saw [it was defined in a header file](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/mutex#L667-L687) and could be activated with `-D_GLIBCXX_HAS_GTHREADS`. After enabling that part of the header and rerun i get the error:

```
In file included from re2/re2.h:196:
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/include/c++\mutex:159:4: error: unknown type name '__gthread_time_t'; did you mean '__gthread_once_t'?
          __gthread_time_t __ts = {
          ^
```

I think this type is defined [here](https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/libgcc/config/gthr-rtems.h#L48) but it's not available in the mingw installation.

I realize it's out of scope for castxml. But i figured i would just report my progress, maybe someone else will stumble on this too.

I will close the issue now, because the remaining problems don't seem to be about castxml

**Comment by flip111** [comment]
Actually i will reopen this for the moment ... because i think i can not solve this by adding source code because there is no source code i believe.

On [mingw forums](https://sourceforge.net/p/mingw-w64/mailman/message/26027623/) it says:

```
>> 3. missing types and functions:
>> __gthread_time_t will have to be defined to time.h's (actually
>> sys/timeb.h's) struct timespec (as in gthr-posix.h).
```

At the moment it seems that the [windows version](https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/i386/gthr-win32.h) of the `gthr-posix.h` file doesn't define these types (and thus that could be the reasons it's not included with mingw).

Is there any way that i can bypass this piece of the source code with castxml ?

**Comment by bradking** [comment]
> CastXML binary ... created July 31, 2019 at 20:54:59.

@thewtex support for LLVM/Clang 9.0 was added to CastXML in August 2019 so that binary could be updated.

With that I'm able to use MinGW g++ 9.2 with `castxml --castxml-cc-gnu g++ test.cxx -std=gnu++14` where `test.cxx` contains `#include <mutex>`.

**Comment by flip111** [comment]
Awesome for looking into it @bradking , i will wait for the new binary release :D

**Comment by flip111** [comment]
Newer binaries have been released. Which can be found through here https://github.com/CastXML/CastXMLSuperbuild which refers to here https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/57b5de948d777f10f2696370

**Comment by jinfagang** [comment]
Does std::once_flag support in mingw?

**Comment by doug65536** [comment]
If someone randomly lands in this ancient bug, because `std::mutex` doesn't compile, even when you `#include <mutex>` and you said `-std=c++11` (or higher), and even said `-pthread`.

I can report that compiling with `x86_64-w64-mingw32-g++-posix` (or x86_64-w64-mingw32-g++-posix) builds code with `std::mutex`, it uses `libpthread-1`.

You should use the `-posix` suffix tools in all cases where one exists for mingw, if you need C++ standard threads. Your libraries should be compiled with it as well.

Also, you should use the `gcc-` prefixed tools where possible:

```
CXX=x86_64-w64-mingw32-g++-posix
CC=x86_64-w64-mingw32-gcc-posix
CPP=x86_64-w64-mingw32-cpp-posix
AR=x86_64-w64-mingw32-gcc-ar-posix
NM=x86_64-w64-mingw32-gcc-nm-posix
RANLIB=x86_64-w64-mingw32-gcc-ranlib-posix
GCOV_DUMP=x86_64-w64-mingw32-gcov-dump-posix
GCOV=x86_64-w64-mingw32-gcov-posix
GCOV_TOOL=x86_64-w64-mingw32-gcov-tool-posix
NM=x86_64-w64-mingw32-gcc-nm-posix
OBJDUMP=x86_64-w64-mingw32-objdump
OBJCOPY=x86_64-w64-mingw32-objcopy
LD=x86_64-w64-mingw32-ld
ADDR2LINE=x86_64-w64-mingw32-addr2line
AS=x86_64-w64-mingw32-as
GPROF=x86_64-w64-mingw32-gprof

```
