### ISSUE TITLE
error: no type named 'unique_ptr' in namespace 'std'

### ISSUE THREAD

**Issue by nnWhisperer** [CastXML/CastXML#157]
when I try to parse a single file in my project, I get many errors and one of them is:
error: no type named 'unique_ptr' in namespace 'std'
Can it be because CastXML doesn't support c++11?
I am trying to compile a single file, however, in the makefile, there are other files used to create a target executable. I have recently begun using CastXML.

**Comment by bradking** [comment]
CastXML supports C++98, C++11, C++14, and C++17.

Please post your `castxml` command-line invocation.

Also, how did you install `castxml`?

**Comment by nnWhisperer** [comment]
I've installed from the ubuntu 16.04 terminal,
when I write "castxml --version", it returned:
castxml version 0.1-g1489405

CastXML project maintained and supported by Kitware (kitware.com).

Ubuntu clang version 3.7.1-1ubuntu4 (tags/RELEASE_371/final) (based on LLVM 3.7.1)
Target: x86_64-pc-linux-gnu
Thread model: posix

**Comment by bradking** [comment]
How are you running `castxml`?  It should be something like `castxml --castxml-cc-gnu g++ mysrc.cxx`.

**Comment by nnWhisperer** [comment]
I am running it through pygccxml

**Comment by bradking** [comment]
CastXML is known to work in general.  There may be a problem with pygccxml or with ubuntu's package.  Please ask for help from those.

**Comment by nnWhisperer** [comment]
Could the reason be that
a) my code is complex and a single target is built with many files. I am using castxml to investigate only a single cpp file. Could that be the reason behind?
b) My code is built with gcc, not clang. As you can see the output I'd posted, my clang version is old 3.7.1. Could this be the reason?
Thank you,

**Comment by bradking** [comment]
It does look like ubuntu 16.04's CastXML and the clang on which it was built are pretty old, but we've supported C++11 from the beginning.

There is a link at the bottom of [this page](https://github.com/CastXML/CastXMLSuperbuild) to CastXML binaries for a newer version.

**Comment by nnWhisperer** [comment]
I guess the reason is, my project is built using makefiles, however CastXML uses cmake and cmakelists to understand the dependency structure.

**Comment by bradking** [comment]
CastXML is not part of the build system and dosen't care about Makefiles or CMake.  It's just a tool like the compiler.

**Comment by nnWhisperer** [comment]
However, instead pf pygccxml, when I use your suggestion, my problem persists:
castxml --castxml-cc-gnu g++ ./long_path/filename.cpp --castxml-gccxml
I get,
"error: use of undeclared identifier 'nullptr'" for the lines similar to:
ClassName* className = nullptr;
in the headerfile.

**Comment by nnWhisperer** [comment]
For future readers:
I gave compiler option to use -std=c++14 and resolved.
Now I am getting an error that was resolved in mid 2016, and the available package in ubuntu LTS16.04 has date February 2016. Therefore, I have removed castxml and I am building using CastXMLSuperbuild.
