### ISSUE TITLE
Debian packaging?

### ISSUE THREAD

**Issue by marvin2k** [CastXML/CastXML#17]
Hi,

will anyone of your team pursue the creation and maintenance of a Debian/Ubuntu package for castxml? See [here](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1326594.html) for example.

**Comment by bradking** [comment]
The process for packaging in Debian has started as discussed [here](http://public.kitware.com/pipermail/castxml/2015-June/000011.html).
