### ISSUE TITLE
Published docs?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [CastXML/CastXML#170]
I see the docs for `pygccxml`:
https://pygccxml.readthedocs.io/en/master/index.html

However, I don't see any for `CastXML`, at least from looking at the `README.rst` / man-page.

**Comment by EricCousineau-TRI** [comment]
Er, oh... the docs are just the CLI manpage... That wasn't immediately clear to me.
Still, would be nice to say something like "We don't have a readthedocs, b/c the only docs are here".

In that case, could the sphinx part just be dropped if it's not really doing anything?

**Comment by bradking** [comment]
The Sphinx infrastructure in CastXML is used to generate the CLI manpage `castxml(1)`.

I don't think many command-line tool packages explicitly state anything about "we don't publish documentation at site X".

**Comment by EricCousineau-TRI** [comment]
Makes sense, but IMO it still seems like the `SPHINX_MAN` is that most useful option so it's clear that's the main use point.
But yeah, and this point, it's just bikeshedding on my part. Thanks!
