### ISSUE TITLE
Add support for simulating compilers with aarch64 targets

### ISSUE THREAD

**Issue by bradking** [CastXML/CastXML#179]
In https://github.com/InsightSoftwareConsortium/ITK/issues/1959#issuecomment-676651534 we discovered that CastXML's [setTriple](https://github.com/CastXML/CastXML/blob/v0.3.4/src/Detect.cxx#L81-L106) does not detect when the compiler given to `--castxml-cc-gnu` targets the `aarch64` architecture.  For example, on a `x86_64` host:

```console
$ castxml --castxml-cc-gnu '(' clang++ -target x86_64-unknown-linux-gnu ')' -v 2>&1 | grep Target
Target: x86_64-unknown-linux-gnu
$ castxml --castxml-cc-gnu '(' clang++ -target i386-unknown-linux-gnu ')' -v 2>&1 | grep Target
Target: i386-unknown-linux-gnu
$ castxml --castxml-cc-gnu '(' clang++ -target aarch64-unknown-linux-gnu ')' -v 2>&1 | grep Target
Target: x86_64-unknown-linux-gnu
```

Note that the determined triple in the last example does not match the `aarch64` architecture.

**Comment by badshah400** [comment]
Many thanks for the quick fix. The update is on its way to openSUSE repos too: <https://build.opensuse.org/request/show/828281>.
