### ISSUE TITLE
__float128 struct dumped to xml file

### ISSUE THREAD

**Issue by iMichka** [CastXML/CastXML#18]
Hi

when using castxml with gcc (GCC 4.8.2,  5.1.0, ```--castxml-cc-gnu /usr/bin/c++```), the xml file contains the unnamed struct for __float128, defined here:
https://github.com/CastXML/CastXML/blob/c113a2b0a0c931f0a83a3cc27f13fd34687a92c0/src/Detect.cxx#L74

This causes two problems:
- the struct's name is empty (which is OK I guess)
- the struct has no file="" definition
- the content of the struct is dumped to the xml file (for example the ```x``` field)

Is it required to dump this definition to the xml file ? We could maybe just not write this part of the tree ? If not, I'll need to adapt pygccxml for this case.

**Comment by bradking** [comment]
If something in the dumped interface references `__float128` then we need to have a node dumped for that reference to be valid.  With gccxml the type was really builtin to the parser so we got

    <FundamentalType id="_2" name="__float128" size="128" align="128"/>

Perhaps we can add a special case to produce this instead of our compatibility struct.

**Comment by bradking** [comment]
Commit b40df94b22507ddb0d5bb2997f29caa47d56a96b should fix this.

**Comment by iMichka** [comment]
Great. Looked at the updated test cases, looks nice. Pygccxml will work with that.

I have a problem though: the FundamentalType node is correctly added, but all the previously mentioned nodes are still there. 

I'm working with an empty .h file, maybe that's the reason ? Or did you have a part of code removing these nodes from the tree which is missing here ?

**Comment by bradking** [comment]
The reason the other nodes still show up is because without `--castxml-start` we dump everything reachable in the translation unit.  The The test case always uses an explicit start option so we don't see that.  I'll look at further hiding this.

**Comment by bradking** [comment]
Commit adcf6a0b51032e4486e1ba0bac3f646166b09653 should hide the extra translation unit member and its members.

**Comment by iMichka** [comment]
Great, works. Thanks a lot for the quick fix.
