### ISSUE TITLE
Working towards dumping Function Bodies

### ISSUE THREAD

**Issue by aiyer-commits** [CastXML/CastXML#186]
Hi, I'm interested in dumping function bodies and would like to contribute. Could you give me an idea of where to start?

**Comment by bradking** [comment]
Thanks for your interest.  However, this is not a design goal of CastXML and is not something we want to support or maintain.

**Comment by aiyer-commits** [comment]
Ok thanks for the info!

Arjun

**Comment by magnusstubman** [comment]
@bradking May I ask why?
