### ISSUE TITLE
Mingw compile error: 'strdup' was not declared in this scope with EncodingCXX.cpp

### ISSUE THREAD

**Issue by intelligide** [CastXML/CastXML#19]
Hello,

I try to build CastXML with MinGW 4.8.1 on Windows 7. I have already compiled LLVM with Clang. But, when I build EncodingCXX.cpp, I obtain 3 errors:
```
'strdup' was not declared in this scope
```
Do you know how to fix it?

Thanks

**Comment by bradking** [comment]
Strange.  The `src/kwsys/EncodingCXX.cxx` does `#include <string.h>` which is supposed to make `strdup` available.

**Comment by intelligide** [comment]
I try to compile with `-std=gnu++0x` but it also does not work.

**Comment by bradking** [comment]
Commit 96c18defee8748369597de557fe0d221c3d2f16c should fix this.
