### ISSUE TITLE
schema

### ISSUE THREAD

**Issue by luke-titley** [CastXML/CastXML#193]
Hey,
The link to the schema in the man page seems out of date.  I was wondering if the schema is still maintained. I'm thinking of generating a struct per xml element type for some rust related work I'm looking at.

**Comment by bradking** [comment]
The schema was just recently added by #184 and is used to verify documents generated by the test suite.  There was one fix in #189.

What is out of date?

**Comment by bradking** [comment]
Cc: @nnemkin

**Comment by luke-titley** [comment]
Ah great!
Well thanks to that schema I was able to make create the structs necessary to load the castxml ast directly into rust.
https://github.com/luke-titley/usd-sys/blob/castXml/cast_xml_schema/src/schema.rs

The link to the schema from the manual page is incorrect. I wasn't sure how old the schema was.

**Comment by bradking** [comment]
At what URL are you viewing the manual such that the link is incorrect?

**Comment by luke-titley** [comment]
https://github.com/CastXML/CastXML/blob/master/doc/manual/castxml.1.rst

**Comment by bradking** [comment]
That's GitHub's rendering of the Sphinx documentation source code.  It doesn't understand the Sphinx `:download:` markup.   Once rendered by Sphinx as HTML, the link is correct.

**Comment by luke-titley** [comment]
oh right. I just checked the manual straight from github, I assumed it was like 'man' like manual page. I didn't realise it was intended to be read only in sphinx. My mistake.
