### ISSUE TITLE
C++ item with multiple annotation produce invalide XML output

### ISSUE THREAD

**Issue by BorisBoucher** [CastXML/CastXML#194]
We are using annotation on C++ enumeration and C++ enumeration items to provides enhanced information.
Since commit bc2de97258f "Output: Generate explicit annotation attributes", CastXML output annotation in a dedicated XML attribute, but this is not correct if the C++ item has more than one annotation.

Exemple of XML output for an enum item with 4 annotations:

    <EnumValue name="MY_ENUM_ITEM" init="3" attributes="annotate(writable()) annotate(range(1.0, 2.0)) annotate(nature(BEAUTIFUL)) annotate(type(DOUBLE))"/>

Once transformed with the last version of CastXML, this leads to the following invalid XML:

    <EnumValue name="MY_ENUM_ITEM" init="3" attributes="annotate(writable()) annotate(range(1.0, 2.0)) annotate(nature(BEAUTIFUL)) annotate(type(DOUBLE))" annotate="writetable()" annotate="range(1.0, 2.0)" annotate="nature(BEAUTIFUL)" annotate(type(DOUBLE)"/>

May be a better approach could be to generate sub elements to store each annotation, eg:

    <EnumValue name="MY_ENUM_ITEM" init="3" attributes="annotate(writable()) annotate(range(1.0, 2.0)) annotate(nature(BEAUTIFUL)) annotate(type(DOUBLE))">
        <Annotate value="writable()"/>
        <Annotate value="range(1.0, 2.0)"/>
        <Annotate value="nature(BEAUTIFUL)"/>
        <Annotate value="type(DOUBLE)"/>
    </EnumValue>

**Comment by bradking** [comment]
@josephsnyder please take a look at this issue.

**Comment by josephsnyder** [comment]
@BorisBoucher, Thank you for the bug report.  Would you be able to send me a C++ block that creates this XML issue?

**Comment by svitoos** [comment]
Imput:

    __attribute__((annotate("attr1")))
    __attribute__((annotate("attr2")))
    void f(void);

Output:

    <Function id="_7" name="f" returns="_13" context="_1" location="f1:3" file="f1" line="3" mangled="_Z1f" annotation="attr1" annotation="attr2" attributes="annotate(attr1) annotate(attr2)"/>

**Comment by bradking** [comment]
Annotations can be on arbitrary declarations.  IIRC our implementation doesn't currently have an easy way to add elements inside other elements, except when the containing element generators explicitly do so.  We're not using a DOM, but just streaming bytes out on the fly.

Please check if there is an XML-ish way to put a list of annotations inside the one `annotate=` attribute.

**Comment by bradking** [comment]
Actually for this particular case, we can just add a newline between each annotation and put them all inside the single `annotate=` attribute.  That will at least make it valid XML.

**Comment by BorisBoucher** [comment]
Thank you for the fast correction.
For info, we are using a post process on the CastXML output to rework the annotation attributes in order to parse the annotation content and insert a sub-tree in the XML element where the annotation was found. 
The resulting XML is then used feeds to an XSL transform that heavily work with the annotation content.

**Comment by todoooo** [comment]
I think the generation of XML sub elements would be preferable to inserting line breaks in an attribute.

**Comment by bradking** [comment]
> I think the generation of XML sub elements would be preferable to inserting line breaks in an attribute.

Implementing that is a hugely invasive change.  We don't use nested elements for anything else not specific to each kind of decl.
