### ISSUE TITLE
C11 _Atomic keyword not supported

### ISSUE THREAD

**Issue by suedlaender83** [CastXML/CastXML#197]
Hello,

I have been working on a project where i need to get xml representation of C source files, collect the size and offset information of the fields in structures, so that i can implement serialiser/deserialiser functions in some scripting languages.

My question is why i can't get the "size" and "align" information for the "atomic basic types" like atomic_uint as in the case of "FundamentalType"? 

Does the "Unimplemented" tag mean that atomic types are not supported yet but will be in future?

 PointerType id="_3196" type="_207" size="64" align="64"
Typedef id="_207" name="atomic_uint" type="_2161" context="_1" location="f14:84" file="f14" line="84"
**Unimplemented id="_2161" type_class="Atomic"**

FundamentalType id="_2131" name="int" size="32" align="32"

Thanks in advance!
Oktay

**Comment by bradking** [comment]
Types like `atomic_uint` are actually typedefs in `<stdatomic.h>` to types defined with the [C11 `_Atomic` keyword](https://en.cppreference.com/w/c/language/atomic).  CastXML does not yet implement support for Clang's `AtomicType` that represents it.

**Comment by bradking** [comment]
@suedlaender83 please see the implementation in #199.
