### ISSUE TITLE
Usage in build system?

### ISSUE THREAD

**Issue by Manouchehri** [CastXML/CastXML#202]
I might be missing something obvious in the docs, but how do most of you use CastXML in larger CMake projects? 

The `man` page shows how to use CastXML manually with one file at a time.. but that's pretty painful when you have a complicated library with hundreds of files you want to use CastXML on.

I'm about to try manually parsing `compile_commands.json` and then rerunning CastXML, though this feels quite hacky and fragile..

**Comment by bradking** [comment]
With CMake one can call `add_custom_command` to run CastXML for each source file to be processed, using e.g. `foreach` to loop over many.  You could ask for help with that over on the [CMake Forums](https://discourse.cmake.org/).

The [ITK](https://github.com/InsightSoftwareConsortium/ITK/) project does this, though their custom commands are added underneath several layers of abstraction that exist within their CMake code.

**Comment by Manouchehri** [comment]
Thank you!
