### ISSUE TITLE
Parsing #defines as constants

### ISSUE THREAD

**Issue by redvers** [CastXML/CastXML#203]
Forgive me if this has been asked before, I searched through issues and was unable to find an answer.

Is there any way that castxml can extract constants from .h files, for example:

```
#define ZIP_ER_OK 0               /* N No error */
#define ZIP_ER_MULTIDISK 1        /* N Multi-disk zip archives not supported */
#define ZIP_ER_RENAME 2           /* S Renaming temporary file failed */
#define ZIP_ER_CLOSE 3            /* S Closing zip archive failed */
#define ZIP_ER_SEEK 4             /* S Seek error */
#define ZIP_ER_READ 5             /* S Read error */
```

I';m suspecting not because it's going to be nuts to try and work out which defines are supposed to be constants and which ones are other things.

If the answer is just "No", please feel free to close this ticket immediately with my thanks in advance.

We're using castxml to generate language bindings for the pony language and it's *exceptional*

Kind Regards,

Red

**Comment by bradking** [comment]
See #21.

**Comment by redvers** [comment]
Thank you for taking the time.  Really appreciate it.
