### ISSUE TITLE
MSVC: Using cl /Zc:wchar_t

### ISSUE THREAD

**Issue by oldmoonagainagain** [CastXML/CastXML#214]
Hi ,
Envirment : x64_x86 Cross Tools Command Prompt for VS 2019 on Windows 10

command: castxml   -c    -x c    --castxml-cc-msvc-c  cl.exe  --castxml-output=1    -o ./data/ast2.xml   ./data/test.h

test.h:
 `typedef wchar_t WCHAR;`

output : 
```
./data/www.h:1:9: error: unknown type name 'wchar_t'
typedef wchar_t WCHAR;
        ^
1 error generated.

```

Adding the following statement at the top of` detect_vs.c `also produces the same error
```
#define _NATIVE_WCHAR_T_DEFINED 1
#define _WCHAR_T_DEFINED 1
```

I want to set argument `/Zc:wchar_t ` for cl.exe to enable internal `wchar_t `support in cl.exe, 
how to do it?

Regards.

**Comment by bradking** [comment]
According to the MSVC documentation for [/Zc:wchar_t](https://docs.microsoft.com/en-us/cpp/build/reference/zc-wchar-t-wchar-t-is-native-type?view=msvc-170), the option is meaningless in C.  It is used only for C++.
