### ISSUE TITLE
How to generate xml description for C++14 file

### ISSUE THREAD

**Issue by Allenhe123** [CastXML/CastXML#215]
Hi,

It work well to generate xml description for C file. But can not do this for C++ file.
I used below command to generate xml description for C++ file:
**_./castxml --castxml-cc-gnu /usr/bin/g++  --castxml-gccxml example.h_**

The error is:
error: invalid argument '-std=gnu++14' not allowed with 'C'

Could you help to give any guide to me, Thanks a lot in advance.

**Comment by bradking** [comment]
The `.h` extension does not automatically correspond to a C++ source file, so you need to add `-x c++` to specify the language of the header.  Also, I suggest using `--castxml-output=1` instead of the legacy `--castxml-gccxml` output mode.  For example:

    ./castxml --castxml-cc-gnu /usr/bin/g++ --castxml-output=1 -x c++ example.h
