### ISSUE TITLE
generate xml description for C++ header file

### ISSUE THREAD

**Issue by Allenhe123** [CastXML/CastXML#217]
I used castxml  to generate a xml description for a c++ .h file.
The .h file is very simple and only two functions in it.
But when i check the generated xml file, it has a lot of lines except the 2 functions.
I just want to dump the functions and structures in the .h file. Is there any option to do this?

PS: I have taken a look at the options, it has so many options.

Thanks a lot in advance.

**Comment by bradking** [comment]
The basic invocation for this use case is

```console
$ castxml -x c++ example.h --castxml-output=1
```

By default all non-template interfaces in the translation unit are dumped.  If you have a `.h` where that doesn't happen, please post a sample.

The only way to limit the output to a subset of the translation unit is to use `--castxml-start <name>` one or more times to name specific starting points.  Often that's used with a namespace.  Only interfaces named or referenced by those named will be included.  There is no way to limit output by source file or header.
