### ISSUE TITLE
debian mipsel build issues

### ISSUE THREAD

**Issue by aborrero** [CastXML/CastXML#22]
Dear developers,

it seems there is something bad for castxml in debian mipsel [0].

There are some tests that are failing.

Some errors are of this kind:
```
236/236 Test #236: gccxml.c++11.GNU-float128-nostart .......................***Failed    0.37 sec
CMake Error at /«BUILDDIR»/castxml-0.1+git20150630/test/run.cmake:97 (message):
  result does not match that expected.

  stderr does not match that expected.

  xml does not match that expected.

  Command was:

   command> "/«BUILDDIR»/castxml-0.1+git20150630/obj-mipsel-linux-gnu/bin/castxml" "--castxml-gccxml" "-std=c++11" "/«BUILDDIR»/castxml-0.1+git20150630/test/input/GNU-float128.cxx" "-o" "gccxml.c++11.GNU-float128-nostart.xml" "--castxml-cc-gnu" "/usr/bin/g++"

  Expected result to match:

   expect-result> 0

  Expected stderr to match:

   expect-stderr> ^$

  Expected xml to match:

   expect-xml> ^<\?xml version="1.0"\?>
   expect-xml> <GCC_XML[^>]*>
   expect-xml> .*<FundamentalType id="_[0-9]+" name="__float128" size="128" align="128"/>.*
   expect-xml>   <File id="f1" name=".*/test/input/GNU-float128.cxx"/>
   expect-xml> </GCC_XML>$

  Actual result:

   actual-result> 1

  Actual stdout:

   actual-stdout> 

  Actual stderr:

   actual-stderr> /«BUILDDIR»/castxml-0.1+git20150630/test/input/GNU-float128.cxx:1:1: error: unknown type name '__float128'
   actual-stderr> __float128 start(__float128);
   actual-stderr> ^
   actual-stderr> /«BUILDDIR»/castxml-0.1+git20150630/test/input/GNU-float128.cxx:1:18: error: unknown type name '__float128'
   actual-stderr> __float128 start(__float128);
   actual-stderr>                  ^
   actual-stderr> 2 errors generated.

  Actual xml:

   actual-xml> (missing)
```

At the end, the tests result is like this:
```
97% tests passed, 6 tests failed out of 236
```

I have a mipsel machine, if you provide me a patch I can do some local tests. Please, let me know if you need additional info.

best regards.

[0] https://buildd.debian.org/status/fetch.php?pkg=castxml&arch=mipsel&ver=0.1%2Bgit20150630-1&stamp=1437262967

**Comment by bradking** [comment]
Thanks.  What is the output of

    $ gcc -c test/input/GNU-float128.c ; echo $?

on this architecture?

**Comment by smr99** [comment]
Brad: did not run your test, but I thought I'd mention that Debian has at least 7 architectures showing the same failure: https://buildd.debian.org/status/package.php?p=castxml&suite=unstable

In each case, all six "float128" tests fail.  Is there a way you can condition the test on the existence of the __float128 type?

**Comment by bradking** [comment]
@smr99 Yes, I've already drafted changes to make the float128 tests conditional based on the results of running `gcc` on the corresponding source file.  That's why I want to verify that `gcc` fails as expected to build the test source file, but I do not have access to the architecture.

**Comment by smr99** [comment]
@bradking: I ran your command on arm64 and mipsel.  Both yielded the same output (I expect all will, since they use the same gcc):

(sid_arm64-dchroot)smr@asachi:~/castxml-0.1+git20150630$ gcc -c test/input/GNU-float128.c ; echo $?
test/input/GNU-float128.c:1:1: error: unknown type name '__float128'
 __float128 start(__float128);
 ^
test/input/GNU-float128.c:1:1: warning: parameter names (without types) in function declaration
1

**Comment by bradking** [comment]
@smr99: Thanks, that is what I was hoping it would do.  I've pushed commit d30d102fbb93bd2267f66ade1da68a0e61c19f97 to enable the float128 tests only if `gcc` has the `__float128` type and can compile the test source file.
