### ISSUE TITLE
Trying to run CastXML on C++ project

### ISSUE THREAD

**Issue by Redstoned** [CastXML/CastXML#222]
I'm working on a c++ project (with CMake) and am trying to generate a xml file from my source code.
I am using MinGW32 as the CMake target (Cmake: -G "MinGW Makefiles") and have compiled the CastXML superbuild from scratch.

When I try to run CastXML on my main.cpp file, I get the error `'glm/vec3.hpp' file not found #include "glm/vec3.hpp"`.
Which it cannot find since the include path is included by my root CmakeLists.txt.

My project has the following structure:
- CMakeLists.txt
- src
- - main.cpp
- - ...
- lib
- - CmakeLists.txt
- - glm
- - - glm/vec3.hpp
- - - ...
- - ...

The glm folder is cloned from [this](https://github.com/g-truc/glm) git repo.

Is there any possibility to use the include paths with CastXML like I could use them with CMake?
Any help would be appreciated!

**Comment by bradking** [comment]
>  the include path is included by my root CmakeLists.txt.

The `include_directories()` or `target_include_directories()` commands add include paths for invocations of the actual compiler.  CastXML is not a compiler, and so you must be using `add_custom_command` or similar to run it.  You need to pass include directories to castxml's invocation in the custom command.

**Comment by Redstoned** [comment]
Thanks for your reply! I used the CPATH environment variable that gets used by clang for additional include paths.
