### ISSUE TITLE
Help: Can I get access to default member initializer?

### ISSUE THREAD

**Issue by MikhailGorobets** [CastXML/CastXML#226]
Can I extract an initialization constant somehow?
For example
```cpp
struct Test {
    int field0 = 0xFF;
    const char* field1 = "test";
};
```
I need to get `0xFF` for `Test::field0` and `"test"` for `Test:field1`

**Comment by bradking** [comment]
This was not previously possible, but I've implemented this in !227.

**Comment by MikhailGorobets** [comment]
@bradking Thanks you!!!

**Comment by MikhailGorobets** [comment]
@bradking Can you add this feature also for generation with `--castxml-gccxml` option ?

**Comment by bradking** [comment]
The `--castxml-gccxml` option exist only for compatibility with projects that haven't been updated to use `--castxml-output=1`.  We don't add new fields to the gccxml mode.

**Comment by MikhailGorobets** [comment]
Got it. Thanks you for the answer!

**Comment by MikhailGorobets** [comment]
[CastXML-python-distributions](https://github.com/CastXML/CastXML-python-distributions) uses this folder
https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/57b5de948d777f10f2696370 for 
creating a python package version. I don't have permission to update this folder. Can you add the latest version of CastXML to this folder?
