### ISSUE TITLE
Should not exit with status 0 on error

### ISSUE THREAD

**Issue by smr99** [CastXML/CastXML#23]
CastXML appears to always exit with status 0 even if, e.g. the input file doesn't exist:

steve@riemann{trunk}castxml a b
error: no such file or directory: 'a'
error: no such file or directory: 'b'
error: no input files
steve@riemann{trunk}echo $?
0

The analogous situation with gccxml did exit non-zero:

steve@riemann{trunk}gccxml a b
gccxml_cc1plus: error: a: No such file or directory
steve@riemann{trunk}echo $?
1

**Comment by bradking** [comment]
Thanks.  Fixed by commit 8a08a44ffee70f71bdb7d8bee90e325dafbfeae4.
