### ISSUE TITLE
linking problem with mingw-w64-i686-clang-3.6.2

### ISSUE THREAD

**Issue by carsten-forty2** [CastXML/CastXML#24]
I experience the following linker problem while building castXML under the current mingw64 and mingw32 environment with respective mingw-w64-*-clang-3.6.2

Scanning dependencies of target cxsys
[  6%] Building C object src/kwsys/CMakeFiles/cxsys.dir/ProcessWin32.c.obj
[ 13%] Building C object src/kwsys/CMakeFiles/cxsys.dir/EncodingC.c.obj
[ 20%] Building C object src/kwsys/CMakeFiles/cxsys.dir/System.c.obj
[ 26%] Building CXX object src/kwsys/CMakeFiles/cxsys.dir/Directory.cxx.obj
[ 33%] Building CXX object src/kwsys/CMakeFiles/cxsys.dir/EncodingCXX.cxx.obj
[ 40%] Building CXX object src/kwsys/CMakeFiles/cxsys.dir/RegularExpression.cxx.obj
[ 46%] Building CXX object src/kwsys/CMakeFiles/cxsys.dir/SystemTools.cxx.obj
[ 53%] Building CXX object src/kwsys/CMakeFiles/cxsys.dir/FStream.cxx.obj
Linking CXX static library ../../lib/libcxsys.a
[ 53%] Built target cxsys
Scanning dependencies of target castxml
[ 60%] Building CXX object src/CMakeFiles/castxml.dir/castxml.cxx.obj
[ 66%] Building CXX object src/CMakeFiles/castxml.dir/Detect.cxx.obj
[ 73%] Building CXX object src/CMakeFiles/castxml.dir/Output.cxx.obj
[ 80%] Building CXX object src/CMakeFiles/castxml.dir/RunClang.cxx.obj
[ 86%] Building CXX object src/CMakeFiles/castxml.dir/Utils.cxx.obj
Linking CXX executable ../bin/castxml.exe
C:\msys32\mingw32\bin/../lib/libclangFrontend.a(CompilerInstance.o):(.text$_ZN5clang11ASTConsumer22GetASTMutationListenerEv[__ZN5clang11ASTConsumer22GetASTMutationListenerEv]+0x0): multiple definition of `clang::ASTConsumer::GetASTMutationListener()'
CMakeFiles/castxml.dir/objects.a(RunClang.cxx.obj):(.text[__ZN5clang11ASTConsumer22GetASTMutationListenerEv]+0x0): first defined here
C:\msys32\mingw32\bin/../lib/libclangFrontend.a(CompilerInstance.o):(.text$_ZN5clang11ASTConsumer29GetASTDeserializationListenerEv[__ZN5clang11ASTConsumer29GetASTDeserializationListenerEv]+0x0): multiple definition of `clang::ASTConsumer::GetASTDeserializationListener()'
CMakeFiles/castxml.dir/objects.a(RunClang.cxx.obj):(.text[__ZN5clang11ASTConsumer29GetASTDeserializationListenerEv]+0x0): first defined here
C:\msys32\mingw32\bin/../lib/libclangFrontend.a(CompilerInstance.o):(.text$_ZNK5clang14FrontendAction20isModelParsingActionEv[__ZNK5clang14FrontendAction20isModelParsingActionEv]+0x0): multiple definition of `clang::FrontendAction::isModelParsingAction() const'
CMakeFiles/castxml.dir/objects.a(RunClang.cxx.obj):(.text[__ZNK5clang14FrontendAction20isModelParsingActionEv]+0x0): first defined here
C:\msys32\mingw32\bin/../lib/libclangFrontend.a(CompilerInstance.o):(.text$_ZN5clang15IdentifierTable3getEN4llvm9StringRefE[__ZN5clang15IdentifierTable3getEN4llvm9StringRefE]+0x0): multiple definition of `clang::IdentifierTable::get(llvm::StringRef)'
CMakeFiles/castxml.dir/objects.a(Output.cxx.obj):(.text[__ZN5clang15IdentifierTable3getEN4llvm9StringRefE]+0x0): first defined here
C:\msys32\mingw32\bin/../lib/libclangFrontend.a(CompilerInstance.o):(.text$_ZN4llvm15SmallVectorImplIN5clang9FixItHintEE5clearEv[__ZN4llvm15SmallVectorImplIN5clang9FixItHintEE5clearEv]+0x0): multiple definition of `llvm::SmallVectorImpl<clang::FixItHint>::clear()'
CMakeFiles/castxml.dir/objects.a(RunClang.cxx.obj):(.text[__ZN4llvm15SmallVectorImplIN5clang9FixItHintEE5clearEv]+0x0): first defined here
C:\msys32\mingw32\bin/../lib/libclangFrontend.a(CompilerInstance.o):(.text$_ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE8_M_eraseEPSt13_Rb_tree_nodeIS5_E[__ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE8_M_eraseEPSt13_Rb_tree_nodeIS5_E]+0x0): multiple definition of `std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_Identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_erase(std::_Rb_tree_node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >*)'
CMakeFiles/castxml.dir/objects.a(castxml.cxx.obj):(.text[__ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_St9_IdentityIS5_ESt4lessIS5_ESaIS5_EE8_M_eraseEPSt13_Rb_tree_nodeIS5_E]+0x0): first defined here
..........................
now following a lot of  'multiple definition of ' errors
..........................

CMakeFiles/castxml.dir/objects.a(Detect.cxx.obj):(.text+0x15fd): undefined reference to `llvm::sys::getDefaultTargetTriple()'
CMakeFiles/castxml.dir/objects.a(RunClang.cxx.obj):(.text+0x5f8): undefined reference to `llvm::sys::getDefaultTargetTriple()'
CMakeFiles/castxml.dir/objects.a(Utils.cxx.obj):(.text+0x734): undefined reference to `llvm::sys::fs::getMainExecutable(char const*, void*)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
src/CMakeFiles/castxml.dir/build.make:305: die Regel für Ziel „bin/castxml.exe“ scheiterte
make[2]: *** [bin/castxml.exe] Fehler 1
CMakeFiles/Makefile2:993: die Regel für Ziel „src/CMakeFiles/castxml.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/castxml.dir/all] Fehler 2
Makefile:126: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

Hopefully you have an idea on how to make castXML running wihin current mingw.
Cheers

**Comment by bradking** [comment]
I was able to build like this:

    $ CC=/mingw32/bin/gcc CXX=/mingw32/bin/g++ cmake ../CastXML -G"Unix Makefiles"

and hacking `src/CMakeFiles/castxml.dir/linklibs.rsp` to replace ` /mingw32` with ` c:/msys32/mingw32`.  The latter step is necessary because `c:/msys32/mingw32/share/llvm/cmake/LLVMExports.cmake` contains MSYS paths instead of Windows paths.

**Comment by bradking** [comment]
I do not think this is a problem with CastXML, but rather with some combinations of:

* msys native v. mingw toolchains
* msys native v. mingw packages

Please check with MSYS2 packagers for LLVM/Clang to see what toolchain should be used to build against the packages.

I'm closing this issue for now since I do not think this is a CastXML bug.  General discussion is better held on the [CastXML mailing list](http://public.kitware.com/mailman/listinfo/castxml).

**Comment by carsten-forty2** [comment]
great 

    CC=/mingw64/bin/gcc CXX=/mingw64/bin/g++ cmake ../CastXML -G"Unix Makefiles
    sed -i -e 's/\/mingw64/C:\/msys64\/mingw64/g' src/CMakeFiles/castxml.dir/linklibs.rsp

works for me .. thanks a lot.
