### ISSUE TITLE
Generating unnecessary syntax  

### ISSUE THREAD

**Issue by mukraj91** [CastXML/CastXML#244]
Hello Team,

We have used below command to parse the simple c++ file, But generated file contains lot's of unnecessary information which is not required.

Could you suggest to generate syntax only contained in source file(test.cpp)

```
castxml test.cpp --castxml-output=1 -o myout.xml
```

test.cpp 

```c++
#include<iostream>
#include<vector>
using namespace std;

int main()
{
vector<int>vec;
vec.reserve(10); // Reserve the size
for(int i = 0 ; i < 32 ; i++) {
	vec.push_back(i);
	cout<< "Size :"<<vec.size() <<" "<<"Capacity: "<<vec.capacity()<<endl;
} 
return 0;
}
```

Regards,
Mukesh K

**Comment by bradking** [comment]
FYI, function bodies are not included.  CastXML only generates information about the interfaces (classes, methods, functions, etc.).  In your example, castxml will dump the signature of `main` and all the code from the C++ standard library included by `iostream` and `vector`.

Add `--castxml-start=main` to limit the output to just the signature of `main` and the types it references.  If your real use case has a namespace, you can use `--castxml-start=$namespace` instead.
