### ISSUE TITLE
mangled key in GCC/MSVC style

### ISSUE THREAD

**Issue by jcerbaro** [CastXML/CastXML#262]
We have an application that is compiled by MSVC, but part of our process involves accessing the 'mangled' key generated by CastXML.

In summary, our problem is that we need CastXML to run knowing that parsing should be based on MSVC, but the style of the mangled key should be as if it were generated by GCC.

Currently, we are using the option `--gccxmlopt=--castxml-cc-gnu g++` to obtain the correct mangled key, but part of the parsing ends up referring to GCC files rather than MSVC.

We need this because we have a routine that uses strings generated by the c++filt command, which takes mangled input in GCC style.

We know that if the mangled key is in MSVC style, we can use the undname command, but this generates strings that do not match our application.

Is it possible to force a change only in the style of generating the mangled key?

**Comment by jcerbaro** [comment]
> The MSVC-style mangling and the GCC-style mangling are different because they implement two distinct and incompatible ABIs: the MSVC ABI and the GNU ABI for Windows (MinGW). CastXML configures its underlying LLVM/Clang to match the ABI of the compiler passed to `--castxml-cc-msvc` or `--castxml-cc-gnu`. There is no way to get mangling from a different ABI.

OK, got it!
Is there any chance we can generate the `demangled` tag as GCC-XML did in the past? That would save us a lot (I mean, A LOT) of trouble. Our older code-base used the demangled string for an introspection library, and this

**Comment by jcerbaro** [comment]
Wow, that actually worked!

Now we can use c++filt to produce the demangled strings we used to get. That will take some processing time but the results will be as expected.

One last problema we have:
We understand that gccxml generated demangled key for a lot of different keys (e.g.: Class), even if that didn't made much sense at the time, but our older code-base used that string for some processing purposes. Now we can't have the demangled key for a class, since we don't have the mangled key for c++filt.

Our workaround is to process the XML file for classes and build the string manually. It works "fine", but if we could reproduce that behaviour just as gccxml, that would be some more spared work!

Thank you for the quick response.

**Comment by bradking** [comment]
Great, I'm glad that worked.  I'll close this as the main issue has been resolved and you have a path forward.

Since classes are not symbols LLVM/Clang does not model any mangling/demangling for them AFAIK.
