### ISSUE TITLE
Use GCC for internal compilation (strange compilation errors?)

### ISSUE THREAD

**Issue by SusanC3** [CastXML/CastXML#266]
The .cpp file I'm trying to convert to XML does not compile successfully with clang (It only compiles with gcc/g++, the compiler my project uses. When I compile with clang I get a compilation error). I set the `--castxml-cc-gnu-c` option to my gcc location, but when I run castxml on my file, I still get the same error that I get when compiling with clang. I tried changing the driver defined in RunClang.cxx:797 to `clang::driver::Driver d("/path/to/bin/gcc", llvm::sys::getDefaultTargetTriple(), *diags);`, but that didn't seem to do anything either.

So, is there any other way to use gcc when castxml compiles my .cpp file? 

Additionally, I have some suspect that this may be a symptom of a different issue, because when I run castxml on other files I sometimes get strange compilation errors (ex, an error that I'm calling a non-static member function without an object when in fact I'm defining the destructor), but all those files include the first file that has the error, so maybe those strange errors are just a result of the first one.

**Comment by bradking** [comment]
I'll close this because there is fundamentally no way to use GCC internally.
