### ISSUE TITLE
Is it possible not to require Clang?

### ISSUE THREAD

**Issue by barracuda156** [CastXML/CastXML#269]
Why is GCC not supported as a compiler?

**Comment by bradking** [comment]
CastXML's implementation is based on the LLVM/Clang AST, which is therefore a fundamental requirement for building Clang itself.  One can still pass `--castxml-cc-gnu g++` at run time to preprocess a translation unit as `g++` would, predefined macros and all.

For reference, CastXML is the successor to [gccxml](https://github.com/gccxml/gccxml), which was based on GCC.

**Comment by barracuda156** [comment]
@bradking Thank you!
