### ISSUE TITLE
Needs LLVMSupport

### ISSUE THREAD

**Issue by solmersa** [CastXML/CastXML#30]
On windows when building needs to link against LLVMSupport so the following should appear on src/CMakeLists.txt

llvm_map_components_to_libnames(llvm_libs
  native
  option
  bitreader
  support
  ${LLVM_TARGETS_TO_BUILD}
  )

**Comment by bradking** [comment]
Against what version of LLVM/Clang are you building (release or SVN rev)?

**Comment by bradking** [comment]
I'm not able to produce a linker error on any platform without this change, but it is indeed a correct change.  Fixed by commit 11e1e5db4699b26ed86be316ab068dbc59b912b0.  Tested with LLVM 3.6, 3.7, and several recent SVN revisions.

**Comment by solmersa** [comment]
I was building against 3.7 release, maybe it is a cmake bug, I am using cmake 3.3.1, the resulting binary castxml.exe has a dependancy of LLVMSupport.dll.  It is Great to have this fixed quickly! Thanks.
