### ISSUE TITLE
Consider tagging a version in sync with ITK releases

### ISSUE THREAD

**Issue by gerddie** [CastXML/CastXML#32]
Hello, 

while I'm well aware of [this post](http://public.kitware.com/pipermail/castxml/2015-June/000012.html) I still think that it would make life of everybody easier if you would tag some release.  Everybody knows that a 0.X release is unstable and may even be buggy but it makes referencing the code a lot easier then pointing to some hash value, also consider the [RERO](https://en.wikipedia.org/wiki/Release_early,_release_often) principle. 

In light that one of the prominent uses of castxml is creating language bindings for ITK you could for instance tag the version that was used when you released the latest ITK version. 

thanks for your consideration, 
Gert

**Comment by bradking** [comment]
As stated in the thread you linked we would like to tag CastXML once it is mature enough for a release.  I think it is close now but haven't had a chance to finalize it yet.

In general projects should not tag themselves with versions of their dependents.  The dependents should refer to the versions of their needed dependencies.  ITK records its version of CastXML via Git SHA-1 in `Wrapping/Generators/CastXML/CMakeLists.txt`:

    GIT_TAG 552dd691215cdafdbe6706e6f76be9d392fb3ffe

**Comment by gerddie** [comment]
Hence  you assume that CastXML with this git SHA-1 is stable enough for doing something, i.e. for creating ITK language bindings. Why not give it a descriptive tag to indicate that? Incidentally  on github this has the nice feature that one can directly get an according tarball, and you could also use this _descriptive_ tag in ITK instead of the git SHA-1. 
This would also make the relationship between projects clearer and easier to document. IMNSHO putting such relationships into the build files somewhere within a project by using svn revisions and git SHA-1 numbers is  bad practise because it disguises these relationships, and I am kind of disappointed that you at Kitware, with  your otherwise  transparent development process do this.

well, that's my $0.02.
