### ISSUE TITLE
offset of base classes is not output in gccxml mode

### ISSUE THREAD

**Issue by doudou** [CastXML/CastXML#34]
gccxml was producing an offset= attribute to the Base tags, that defines the offset of a base class within the subclass. castxml removed that attirbute. Would be great if it could be added back.

**Comment by bradking** [comment]
Thanks for pointing this out.

This information may be accessible from Clang through something like `clang::ASTRecordLayout::getBaseClassOffset`.  Some investigation will be needed to determine exactly what offset gccxml would print out here for various cases, and whether the information was even correct in the case of virtual inheritance.

**Comment by bradking** [comment]
For reference, gccxml generates the `Base` element `offset` attribute [here](https://github.com/gccxml/gccxml/blob/3afa8ba5be6866e603dcabe80aff79856b558e24/GCC/gcc/cp/xml.c#L2362-L2367).  The `BINFO_OFFSET` macro is defined [here](https://github.com/gccxml/gccxml/blob/3afa8ba5be6866e603dcabe80aff79856b558e24/GCC/gcc/tree.h#L2164-L2170) and documented as:

> The offset where this basetype appears in its containing type. ... offset (in bytes) from the base of the complete object to the base of the part of the object that is allocated on behalf of this `type'.  This is always 0 except when there is multiple inheritance.

**Comment by bradking** [comment]
Implemented by commit 96b5c2d10b2f6712a55be56ad58190ca19707634.

**Comment by doudou** [comment]
Awesome, thanks !
