### ISSUE TITLE
Link error when building castxml: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> 

### ISSUE THREAD

**Issue by chenghuige** [CastXML/CastXML#39]
ScaledNumber.cpp:(.text._ZN4llvm16ScaledNumberBase8toStringB5cxx11Emsij+0x602): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
    ScaledNumber.cpp:(.text._ZN4llvm16ScaledNumberBase8toStringB5cxx11Emsij+0x72d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
    ScaledNumber.cpp:(.text._ZN4llvm16ScaledNumberBase8toStringB5cxx11Emsij+0x878): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'

**Comment by bradking** [comment]
Against what version of LLVM/Clang are you building?  On what platform?

**Comment by chenghuige** [comment]
@bradking  
llvm 3.6.0-1
inux version 2.6.32_1-4-0-0 (scmpf@bb-stlnhw02.bb01.baidu.com) (gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) ) #1 SMP Wed Mar 14 19:10:34 CST 2012

**Comment by bradking** [comment]
This looks like a possible mismatch between the c++ dialect and/or c++ standard library used to build LLVM/Clang and that used to build CastXML.  There is a similar problem discussed [here](http://stackoverflow.com/questions/4808165/c-std-library-linking-with-different-c-standards).

**Comment by bradking** [comment]
> llvm 3.6.0-1

Be sure to compile CastXML using a compatible compiler, `-std=` dialect, etc. as was used when the `llvm` package was built by the distribution.  Otherwise you are trying to link CastXML to static LLVM/Clang libraries without also linking to a compatible C++ runtime library on which LLVM/Clang depends.
