### ISSUE TITLE
No such path for LLVM_DIR

### ISSUE THREAD

**Issue by dthummel** [CastXML/CastXML#41]
Hello!

Hopefully you can give me a hint to the build instructions. I have downloaded llvm and clang (3.7) and have done a build. Because llvm does not allow me to do an in-source-tree build I have done an out-of-source-tree-build. This worked like a charm. Now I would like to build CastXML on top of this. The build instructions say to set LLVM_DIR to <prefix>/share/llvm/cmake.

Now my problem is the following: A subdirectory structure share/llvm/cmake exists only in the build directory. If I set LLVM_DIR to this path, cmake complains that I must set it to a LLVM/clang SDK source tree, not a build tree. But in the source tree there is no such directory structure. If I set the LLVM_DIR variable to <my-source-tree>/share/llvm/cmake even if it does not exist, cmake complains about a missing FindLLVM.cmake. So what path should I use for LLVM_DIR?

Regards
Dietmar

**Comment by dthummel** [comment]
Notice: Sadly github removed the path prefixes that I added. So, once again with a slightly different notation:

Hello!

Hopefully you can give me a hint to the build instructions. I have downloaded llvm and clang (3.7) and have done a build. Because llvm does not allow me to do an in-source-tree build I have done an out-of-source-tree-build. This worked like a charm. Now I would like to build CastXML on top of this. The build instructions say to set LLVM_DIR to PREFIX/share/llvm/cmake.

Now my problem is the following: A subdirectory structure share/llvm/cmake exists only in the build directory. If I set LLVM_DIR to this path (BUILD/share/llvm/cmake), cmake complains that I must set it to a LLVM/clang SDK source tree, not a build tree. But in the source tree there is no such directory structure. If I set the LLVM_DIR variable to SOURCE/share/llvm/cmake even if it does not exist, cmake complains about a missing FindLLVM.cmake. So what path should I use for LLVM_DIR?

Regards
Dietmar

**Comment by thewtex** [comment]
Hello,

LLVM_DIR should be set to the path to PREFIX/share/llvm/cmake, which should contain the file LLVMConfig.cmake.  This path is in the install tree PREFIX, not just a build tree.

Please send these questions to the mailing list instead of opening an issue.

Hope this helps,
Matt
