### ISSUE TITLE
liblldConfig.a not found (cmake win7/msys)

### ISSUE THREAD

**Issue by lrs-123** [CastXML/CastXML#43]
Am attempting to build CastXML on Windows 7 using MINGW/MSYS2.

When running the command ```cmake -G 'Unix Makefiles' ../castXML``` from a build directory, the following error occurs:

    CMake Error at C:/msys64/mingw64/share/llvm/cmake/LLVMExports.cmake:685 (message):
      The imported target "lldConfig" references the file
         "C:/msys64/mingw64/lib/liblldConfig.a"    
      but this file does not exist.  Possible reasons include:    
      * The file was deleted, renamed, or moved to another location.    
      * An install or uninstall procedure did not complete successfully.    
      * The installation package was faulty and contained    
         "C:/msys64/mingw64/share/llvm/cmake/LLVMExports.cmake"    
      but not all the files it references.
    Call Stack (most recent call first):
      C:/msys64/mingw64/share/llvm/cmake/LLVMConfig.cmake:120 (include)
      CMakeLists.txt:64 (find_package)

There exists no ```liblldConfig.a``` in the MinGW installation of LLVM, and I can't find any info online. Prior to the error, CMake checks all come through OK:

    -- The C compiler identification is GNU 5.3.0
    -- The CXX compiler identification is GNU 5.3.0
    -- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
    -- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe
    -- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found Git: C:/msys64/usr/bin/git.exe (found version "2.7.0")
    -- Checking whether header cstdio is available
    -- Checking whether header cstdio is available - yes
    -- Checking for Large File Support
    -- Checking for Large File Support - yes
    -- Checking whether C compiler has ptrdiff_t in stddef.h
    -- Checking whether C compiler has ptrdiff_t in stddef.h - yes
    -- Checking whether C compiler has ssize_t in unistd.h
    -- Checking whether C compiler has ssize_t in unistd.h - yes

**Comment by bradking** [comment]
This looks like an incorrect installation of LLVM CMake package files by the package manager.  What package version do you have installed?

    $ pacman -Qs llvm

**Comment by lrs-123** [comment]
Looks like 3.7.0-9

    $ pacman -Qs llvm
    local/mingw-w64-x86_64-clang 3.7.0-9
        C language family frontend for LLVM
    local/mingw-w64-x86_64-llvm 3.7.0-9
        Low Level Virtual Machine (mingw-w64)

**Comment by bradking** [comment]
Thanks.  I've reproduced that environment:

    $ pacman -Qs llvm
    local/mingw-w64-x86_64-clang 3.7.0-9
        C language family frontend for LLVM
    local/mingw-w64-x86_64-llvm 3.7.0-9
        Low Level Virtual Machine (mingw-w64)

but I get an earlier error:

    $ cmake -G 'Unix Makefiles' ../CastXML 
    CMake Error at C:/msys64/mingw64/share/llvm/cmake/LLVMConfig.cmake:131 (include):
      include could not find load file:

        D:/develop/scripts/mingw-w64-clang/src/build-x86_64/share/llvm/cmake/LLVMExports.cmake

It looks like the package includes the `LLVMConfig.cmake` from the build tree, as I see this content:

    # LLVM_BUILD_* values available only from LLVM build tree.
    set(LLVM_BUILD_BINARY_DIR "D:/develop/scripts/mingw-w64-clang/src/build-x86_64")
    set(LLVM_BUILD_LIBRARY_DIR "D:/develop/scripts/mingw-w64-clang/src/build-x86_64/./lib")
    set(LLVM_BUILD_MAIN_INCLUDE_DIR "D:/develop/scripts/mingw-w64-clang/src/llvm-3.7.0.src/include")
    set(LLVM_BUILD_MAIN_SRC_DIR "D:/develop/scripts/mingw-w64-clang/src/llvm-3.7.0.src")

This is incorrect.  The package should use the `LLVMConfig.cmake` produced by CMake's `make install` rule.

Please raise this with the MSYS2 packagers.

Meanwhile you may be able to proceed by building LLVM/Clang from source yourself.

**Comment by lrs-123** [comment]
I'll try that.

Thanks a lot for the help!
