### ISSUE TITLE
CastXML doesn't like "override" 

### ISSUE THREAD

**Issue by gerddie** [CastXML/CastXML#45]
Hi, 

now I get the following error: 

Generating itkLevelSetFunction.xml
cd /home/gerddie/Debian/build-area/insighttoolkit4-4.8.2/BUILD/Wrapping/Modules/ITKLevelSets && /usr/local/bin/castxml -o /home/gerddie/Debian/build-area/insighttoolkit4-4.8.2/BUILD/Wrapping/Modules/ITKLevelSets/itkLevelSetFunction.xml --castxml-gccxml --castxml-start _cable_ --castxml-cc-gnu /usr/bin/g++-6 -w -c @/home/gerddie/Debian/build-area/insighttoolkit4-4.8.2/BUILD/Wrapping/Modules/ITKLevelSets/castxml.inc /home/gerddie/Debian/build-area/insighttoolkit4-4.8.2/BUILD/Wrapping/Modules/ITKLevelSets/itkLevelSetFunction.cxx

    In file included from /home/gerddie/Debian/build-area/insighttoolkit4-4.8.2/BUILD/Wrapping/Modules/ITKLevelSets/itkLevelSetFunction.cxx:20:
      /home/gerddie/Debian/build-area/insighttoolkit4-4.8.2/Modules/Segmentation/LevelSets/include/itkLevelSetFunction.h:181:21: error: 
            'ComputeUpdate' marked 'override' but does not override any member functions
            virtual PixelType ComputeUpdate( const NeighborhoodType & neighborhood,
                    ^
        /home/gerddie/Debian/build-area/insighttoolkit4-4.8.2/BUILD/Wrapping/Modules/ITKLevelSets/itkLevelSetFunction.cxx:31:18: note: in
           instantiation of template class 'itk::LevelSetFunction<itk::Image<float, 2> >' requested here
    typedef itk::LevelSetFunction< itk::Image< float,2 > >::Pointer itkLevelSetFunctionIF2_Pointer;

Obviously another C++11 issue, but I have no idea why this goes wrong, AFAIKS the override is perfectly valid.

**Comment by thewtex** [comment]
Did this patch address the issue?:

  http://review.source.kitware.com/#/c/20673/

**Comment by gerddie** [comment]
Yes, closing this, because castxml did exactly what it was suppose to do.
