### ISSUE TITLE
__builtin_va_arg_pack not supported by castxml

### ISSUE THREAD

**Issue by gerddie** [CastXML/CastXML#46]
The problem is triggered by compiling ITK-4.9 using the host compiler g++-5.3.1. and is actually already reported for [llvm upstream](https://llvm.org/bugs/show_bug.cgi?id=7219). 

Specifically, I get 

    cd /home/gerddie/build-area/insighttoolkit4-4.9.0/BUILD/Wrapping/Modules/ITKImageFilterBase && /usr/bin/castxml -o /home/gerddie/build-area/insighttoolkit4-4.9.0/BUILD/Wrapping/itkRecursiveSeparableImageFilter.xml --castxml-gccxml --castxml-start _wrapping_ --castxml-cc-gnu "(" /usr/bin/c++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel ")" -w -c @/home/gerddie/build-area/insighttoolkit4-4.9.0/BUILD/Wrapping/ITKImageFilterBase.castxml.inc /home/gerddie/build-area/insighttoolkit4-4.9.0/BUILD/Wrapping/itkRecursiveSeparableImageFilter.cxx

    In file included from /home/gerddie/build-area/insighttoolkit4-4.9.0/BUILD/Wrapping/itkRecursiveSeparableImageFilter.cxx:1:
    In file included from /home/gerddie/build-area/insighttoolkit4-4.9.0/Modules/Core/Common/include/itkCommand.h:21:
    In file included from /home/gerddie/build-area/insighttoolkit4-4.9.0/Modules/Core/Common/include/itkObject.h:31:
    In file included from /home/gerddie/build-area/insighttoolkit4-4.9.0/Modules/Core/Common/include/itkLightObject.h:21:
    In file included from /home/gerddie/build-area/insighttoolkit4-4.9.0/Modules/Core/Common/include/itkMacro.h:47:
    In file included from /usr/include/c++/5/string:40:
    In file included from /usr/include/c++/5/bits/char_traits.h:40:
    In file included from /usr/include/c++/5/bits/postypes.h:40:
    In file included from /usr/include/c++/5/cwchar:44:
    In file included from /usr/include/wchar.h:884:
        /usr/include/x86_64-linux-gnu/bits/wchar2.h:291:14: error: use of undeclared identifier '__builtin_va_arg_pack'
                           __fmt, __va_arg_pack ());
                                  ^
        /usr/include/x86_64-linux-gnu/sys/cdefs.h:349:26: note: expanded from macro '__va_arg_pack'
            # define __va_arg_pack() __builtin_va_arg_pack ()

g++ --version: g++ (Debian 5.3.1-7) 5.3.1 20160121 

Surprisingly, this didn't show up with g++-6.

**Comment by bradking** [comment]
The error occurs in standard library code guarded by `#if __USE_FORTIFY_LEVEL > 1` which is defined in `features.h` via:

    #if defined _FORTIFY_SOURCE && _FORTIFY_SOURCE > 0 \
        && __GNUC_PREREQ (4, 1) && defined __OPTIMIZE__ && __OPTIMIZE__ > 0
    # if _FORTIFY_SOURCE > 1
    #  define __USE_FORTIFY_LEVEL 2
    ...

Therefore one must have optimizations enabled and add  `-D_FORTIFY_SOURCE=2`.

I'm able to reproduce this using

    --castxml-cc-gnu "(" /usr/bin/c++ -O1 -D_FORTIFY_SOURCE=2  ")"

**Comment by bradking** [comment]
Fixed by commit 1489405912947356574477a3c10fec69e78cb6dc.
