### ISSUE TITLE
Invalid qualified enum name

### ISSUE THREAD

**Issue by praetorian20** [CastXML/CastXML#52]
Found a bug with `enum` qualification. Given this code

```
namespace fx{
    enum{ unnamed = 0 };
    void fix_unnamed( int x=unnamed );
}
```
latest CastXML is generating
```
  <Enumeration id="_1162" name="" ...>
    <EnumValue name="unnamed" init="0"/>
  </Enumeration>
  <Function id="_1163" name="fix_unnamed" ...>
    <Argument name="x" ... default="fx::::unnamed"/>
  </Function>
```
The default value is being generated as `fx::::unnamed` because the `enum` doesn't have a name.

**Comment by bradking** [comment]
Thanks.  Fixed by commit 1604e1a7ac8d417509c656135eff489ea970e4d2.
