### ISSUE TITLE
Problem with castxml 

### ISSUE THREAD

**Issue by kodaz1** [CastXML/CastXML#53]
I'm trying to install pygimli. All things seems to be ok except the building o castxml . 
I have the following message : 
/home/arfang/gimli/thirdParty/src/castXML/src/Output.cxx:21:34: fatal error: clang/AST/ASTContext.h: Aucun fichier ou dossier de ce type
 #include "clang/AST/ASTContext.h"
                                  ^
compilation terminated.
/home/arfang/gimli/thirdParty/src/castXML/src/RunClang.cxx:24:35: fatal error: clang/AST/ASTConsumer.h: Aucun fichier ou dossier de ce type
 #include "clang/AST/ASTConsumer.h"
                                   ^
compilation terminated.
make[2]: *** [src/CMakeFiles/castxml.dir/Output.cxx.o] Erreur 1
make[2]: *** Attente des tâches non terminées....
make[2]: *** [src/CMakeFiles/castxml.dir/RunClang.cxx.o] Erreur 1
make[1]: *** [src/CMakeFiles/castxml.dir/all] Erreur 2
make: *** [all] Erreur 2
~/gimli/thirdParty
-- NOT Found castxml executable: cannot build pygimli.
I don't know what to  do with this issue. 
I try to built castxml with gcc or with clang but i got the same error. 
Thank you for your help cause i don't know how to deal with this issue.

**Comment by bradking** [comment]
What is the value of LLVM_DIR in the CMakeCache.txt in the CastXML build tree?

**Comment by kodaz1** [comment]
The LLVM_DIR in CMakeCache.txt is : 
LLVM_DIR:PATH=/usr/share/llvm-3.7/cmake

**Comment by bradking** [comment]
What Linux distro are you using?

**Comment by bradking** [comment]
Debian packages of LLVM/Clang may be breaking the CMake files by moving things around post-installation:

* http://thread.gmane.org/gmane.comp.compilers.llvm.cvs/255502/focus=255724
* https://llvm.org/bugs/show_bug.cgi?id=24154#c27

**Comment by kodaz1** [comment]
I'm using Ubuntu Trusty : Linux version 3.13.0-83-generic (buildd@lgw01-53) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) )

**Comment by bradking** [comment]
Please make sure the `libclang-3.7-dev` package is installed.

**Comment by kodaz1** [comment]
It seems that i think the problem with castxml is solved :+1:  when i install libclang-3.7-dev even if i still have some problems to install pygimli cause with a python error :
RuntimeError: `Py++` is going to write different content to the same file(./generated/ContainerType.pypp.hpp).
The following is a short list of possible explanations for this behaviour:
* `Py++` bug, in this case, please report it
* module_builder_t contains two or more classes with the same alias
* module_builder_t contains two or more classes with the same wrapper alias
Please carefully review `Py++` warning messages. It should contain an additional information.
make[3]: *** [pggen] Erreur 1
make[2]: *** [python/CMakeFiles/pggen.dir/all] Erreur 2
make[1]: *** [CMakeFiles/pygimli.dir/rule] Erreur 2
make: *** [pygimli] Erreur 2

Thank you for your help

**Comment by bradking** [comment]
Great.  `Py++` is a separately maintained project so such issues could be raised there, or possibly in the intermediary [pygccxml](https://github.com/gccxml/pygccxml/).  They can determine whether there is a remaining CastXML issue in this use case.
