### ISSUE TITLE
Building castxml with clang3.8

### ISSUE THREAD

**Issue by kodaz1** [CastXML/CastXML#58]
Hello, 
I'm trying to build castxml with clang3.8 but it doesn't work. I have the following error : 
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  
include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  CMakeLists.txt:64 (find_package)

CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  CMakeLists.txt:64 (find_package)

CMake Error at src/CMakeLists.txt:46 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".

-- Configuring incomplete, errors occurred!

Do you have an idea on what is happening if you have a little time to take a look on it.
Thank you for your help.

**Comment by bradking** [comment]
This is due to a [Debian packaging bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819072).  I've given them detailed instructions on how to fix it but they have not updated the package yet AFAIK.  You could try pinging the issue over there.

**Comment by kodaz1** [comment]
Thank you Bradking, 
I will downgrade to clang 3.7 and llvm3.7 cause last time after installing libclang3.7-dev as you said things was ok .

**Comment by kodaz1** [comment]
the build is successful after downgrading 
thx :)
