### ISSUE TITLE
CastXML has a problem with __float128 on GCC-6.1

### ISSUE THREAD

**Issue by Richard-Gmac** [CastXML/CastXML#59]
Using CastXML-41581db, pygccxml-1.7.4 and the most recent pyplusplus from the ompl bitbucket repo. Seems to be related to issue #45. I also tried -std=c++14 and got past this problem, but had other problems with empty declaration names (in bits/hashtable.h via unordered_map).

$ g++ --version
g++ (GCC) 6.1.0

castxml  -I/path/to/boost-1_60 -c -x c++ --castxml-cc-gnu /path/to/g++ -std=gnu++14 --castxml-gccxml -o /tmp/tmpCYMyX0.xml boost-1_60/boost/type_traits/type_with_alignment.hpp
boost-1_60/boost/type_traits/type_with_alignment.hpp:48:21: error:
      support for type '__float128' is not yet implemented
         __float128 f128;
                    ^
1 error generated.

**Comment by bradking** [comment]
Thanks.  Fixed by commit 9a834141a84c4839949826c7f70b944ffea07b80.

**Comment by Richard-Gmac** [comment]
Patch works great, though I get the same problems with empty symbols  and errors that look like:

`  File "/home/isd/rgould1/Source/git/vogue/external/all/python/pygccxml/declarations/declaration.py", line 343, in create_decl_string
    return algorithm.full_name(self, with_defaults)
  File "/home/isd/rgould1/Source/git/vogue/external/all/python/pygccxml/declarations/algorithm.py", line 128, in full_name
    declaration_path(decl))
  File "/home/isd/rgould1/Source/git/vogue/external/all/python/pygccxml/declarations/algorithm.py", line 107, in full_name_from_declaration_path
    result = result[0] + '::'.join(result[1:])
IndexError: list index out of range
`

I realise this is a separate issue, but I don't have a good small case to reproduce it. From what I can see in the debugger, it is related to the gcc headers unordered_map and bits/hashtable.h. I've patched it in declarations/algorithm.py with

```
     if result==[]:
         result=''
     else:
         result = result[0] + '::'.join(result[1:])

```

which is allowing me to build and pass all my tests, but this doesn't feel like a good solution.

**Comment by iMichka** [comment]
Hi. Seems to be the error described there: https://github.com/gccxml/pygccxml/issues/47
We can continue the discussion there.
