### ISSUE TITLE
Assertion "Name.isIdentifier() && "Name is not a simple identifier"" failed

### ISSUE THREAD

**Issue by j-santander** [CastXML/CastXML#62]
Parsing `<string>`, castxml shows:

> assertion "Name.isIdentifier() && "Name is not a simple identifier"" failed: file "/usr/include/clang/AST/Decl.h", line 169, function: llvm::StringRef clang::NamedDecl::getName() const
> Aborted
> 

Steps to reproduce:

1. Using clang 3.7.1 on cygwin Windows 7 (Target: i686-pc-windows-cygnus) installed from latest cygwin
2. Downloaded latest CastXML (9a834141a84c4839949826c7f70b944ffea07b80)
3. cmake . && make install

using a simple file `test.C`
```c++
#include <string>
```

> $ castxml.exe -x c++ --castxml-gccxml test.C
> assertion "Name.isIdentifier() && "Name is not a simple identifier"" failed: file "/usr/include/clang/AST/Decl.h", line 169, function: llvm::StringRef clang::NamedDecl::getName() const
> Aborted
> 

This problem has apparently been discussed at https://www.mail-archive.com/rock-dev@dfki.de/msg01885.html

Looking at the change reported there as culprit (917c646ed9e29ca57fd53791a9b3f5f97e86d8b9), the answer to the following question (http://comments.gmane.org/gmane.comp.compilers.clang.devel/48763) seems to suggest a solution.

**Comment by bradking** [comment]
Fixed and test case added.  Thanks for your help.

It's too bad no one from the thread you linked reported this earlier, or it could have been fixed much sooner after it was introduced.  My use cases for CastXML always use `--castxml-start` which never walks the translation unit decls so the offending code is never hit.
