### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by c4xdiscovery** [CastXML/CastXML#64]
As per instruction on [clang.llvm](http://clang.llvm.org/get_started.html) and since the revision number is reported to have been tested, I did: 

```
svn co -r 267153 http://llvm.org/svn/llvm-project/llvm/trunk llvm
cd llvm/tools
svn co -r 267153 http://llvm.org/svn/llvm-project/cfe/trunk clang (did I choose the right revision? )
cd ../..
```
and then ran cmake on it and then

```
cmake --build .
cmake --build --target install
```

and it installed fine.

Having checked out CastXML, I tried running cmake on it. I tried:

`cmake -D LLVM_DIR=path\to\installed\llvm\ -D CLANG_RESOURCE_DIR=path\to\installed\llvm\lib\clang\3.9.0 ..\CastXML`

I got the error about the find modules not being found. I then tried:

`cmake -D CMAKE_PREFIX_PATH=path\to\downloaded\llvm\cmake\modules -D CLANG_RESOURCE_DIR=path\to\installed\llvm\lib\clang\3.9.0 ..\CastXML`

and I get:

_CMake Error at C:/Users/VR/llvm/cmake/modules/LLVM-Config.cmake:203 (message):
  Library `option' not found in list of llvm libraries._

Have I got the wrong version of CLang source file?

**Comment by bradking** [comment]
Please try configuring CastXML in a fresh build tree with

    cmake -DCMAKE_PREFIX_PATH=C:/path/to/llvm-install-prefix ..\CastXML

where `llvm-install-prefix` is the `CMAKE_INSTALL_PREFIX` used when building LLVM/Clang.  The value of `CLANG_RESOURCE_DIR` should be computed automatically if LLVM is found properly.

If you still get the error please attach the `LLVMConfig.cmake` file that sits next to `LLVM-Config.cmake` (note the lack of `-` in the former's name).

**Comment by c4xdiscovery** [comment]
I didn't specify a CMAKE_INSTALL_PREFIX path and it installed in the default location. So I tried your suggestion with C:\Program Files (x86)\LLVM. It still gives me the same error. 
I can see that there is a config file at: C:\Program Files (x86)\LLVM\lib\cmake\llvm. I tried trying your suggestion with that one but that too didn't work.
I have attached the install tree config files here:
[llvm-install-config-files.zip](https://github.com/CastXML/CastXML/files/325939/llvm-install-config-files.zip)

also here is the build tree config file: 
[llvm build tree config files.zip](https://github.com/CastXML/CastXML/files/325947/llvm.build.tree.config.files.zip)

command line screenshot:

**Comment by bradking** [comment]
From the screenshot:

> cmake -D CMAKE_PREFIX_PATH=C:\Program Files (x86)\LLVM\ ..\CastXML

You're not quoting the path with spaces.  Please try:

    cmake -DCMAKE_PREFIX_PATH="C:/Program Files (x86)/LLVM" ..\CastXML

**Comment by c4xdiscovery** [comment]
Ha, thanks. that did it. I got 219 warnings though.

**Comment by bradking** [comment]
Great.
