### ISSUE TITLE
CMake can't find libLLVMSupport.a

### ISSUE THREAD

**Issue by mtnakayama** [CastXML/CastXML#65]
I'm having difficulty building CastXML on my Fedora 24 installation. I have Cmake version 3.8.0
This is as far as I got:

CMake Error at /usr/share/llvm/cmake/LLVMExports.cmake:829 (message):
  The imported target "LLVMSupport" references the file`

    "/usr/lib64/libLLVMSupport.a"

 ` but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/share/llvm/cmake/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/share/llvm/cmake/LLVMConfig.cmake:152 (include)
  CMakeLists.txt:64 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/matthew/Downloads/CastXML/CMakeFiles/CMakeOutput.log".
[CMakeOutput.log.txt](https://github.com/CastXML/CastXML/files/331234/CMakeOutput.log.txt)

**Comment by bradking** [comment]
As the error message explains this is likely a packaging problem for LLVM/Clang on the relevant distro.  Please raise this with them.

**Comment by panzy** [comment]
try installing llvm-static.
