### ISSUE TITLE
Wrong decl_type for function pointers ?

### ISSUE THREAD

**Issue by teto** [CastXML/CastXML#67]
Similarl to #66, when the argument is a function pointer, there seems to be a few problems:

For instance for the function `int atexit(void (*function)(void));`, the pygccxml code `decl.arguments[0].decl_type` returns: `void (*)(  ) *` which has 1 more asterisk then necessary ?

**Comment by iMichka** [comment]
This looks like a bug. Could you please open an issue on the pygccxml bug tracker ?
https://github.com/gccxml/pygccxml/issues

The decl_type / decl_string creating is more on pygccxml's side than on castxml's.

Please precise which compiler you are using in the new issue.

**Comment by teto** [comment]
sorry ! Indeed I wanted to post both issues on pygccxml's instead of here. In a moment of distraction, I ended up confusing castxml & pygccxml sorry :/
