### ISSUE TITLE
What format is recommended for new scripts?

### ISSUE THREAD

**Issue by ctrlcctrlv** [CastXML/CastXML#68]
The documentation says:

>--castxml-gccxml
    Generate XML output in a format close to that of gccxml. Write output to <src>.xml or file named by -o. The gccxml format does not support Clang language modes other than -std=c++98 or -std=c89. This output format may be used with language modes -std=c++11, -std=c++14, -std=c99, and -std=c11 but the output will not contain implicit move constructors or move assignment operators, and may contain <Unimplemented/> elements on non-c++98 constructs.

So what flag/format is recommended for scripts that don't rely on GCCXML's format, and so can support those Unimplemented features? Or does it not yet exist?

**Comment by bradking** [comment]
No other format yet exists.  The name `--castxml-gccxml` was chosen for the current output format since the goal was to reproduce gccxml's format.  The name leaves room for adding more formats later with differently-named options, but actually adding them is not currently a goal.
