### ISSUE TITLE
please add support for alias declarations

### ISSUE THREAD

**Issue by mamoll** [CastXML/CastXML#69]
It looks like CastXML doesn't support C++11 [alias declarations](http://en.cppreference.com/w/cpp/language/type_alias). For example, when parsing this code:
```
#include <memory>
using intptr = std::shared_ptr<int>;
```
no type info can be found for `intptr` in the output. Treating them as typedefs would be a good first step. Support for alias templates seems much harder.

**Comment by bradking** [comment]
Currently CastXML's only goal is to reproduce gccxml's output for C++98 interfaces.  Extending it to C++11 will require a new output-activation option different than `--castxml-gccxml`, design of the new format, tests, etc.  It is not a step to be taken lightly.

**Comment by praetorian20** [comment]
@bradking Agreed that supporting alias templates in their entirety might be a whole new feature, but is there any harm to adding support for the case that Mark describes? Couldn't CastXML generate identical XML representations for the following declarations and not break gccxml compatibility?

```
typedef int Integer;
using Integer = int;
```

**Comment by bradking** [comment]
> generate identical XML representations for the following declarations

I'd prefer not to misrepresent what is in the source.

Closing in favor of #72, which serves as a placeholder for addition of new output formats.

**Comment by nak** [comment]
I would think you could at least output (1) the context in the undefined element to tell in what namespace/class it appeared (I'm assuming this is already available at the point where an unknown item such as TypeAliasDecl appears).  and (2) output the raw AST output text if you are indeed using clang's AST output as a precursor to generating the XML
