### ISSUE TITLE
Usage information is a bit vague on --castxml-cc-<id>

### ISSUE THREAD

**Issue by brianthelion** [CastXML/CastXML#7]
This goes for both the `man` page and for the `--help`:
```
  --castxml-cc-<id> <cc>
  --castxml-cc-<id> "(" <cc> <cc-opt>... ")"
    Simulate given <id>-like compiler command, where <id> is
    one of: gnu, msvc
```
In particular, what are `<cc>` and `<cc-opt>` meant to represent here? The `man` page says "the given compiler command" but as a naive user it's not entirely clear what that means. In the case of `--cast-xml-gnu` I'm assuming this means, notionally, "anything that you'd put on the command line after `g++` except the file name". Is that accurate?

A practical example would go a long way for us n00bs here.

Thanks!

**Comment by bradking** [comment]
Thanks.  I've updated the documentation and `--help` output in commit 99f6437d1d77094fbb97f9c66005bac5af086778 to specify the meaning of `<cc>` and `<cc-opt>...`.

**Comment by brianthelion** [comment]
Cheers!
