### ISSUE TITLE
Add new non-gccxml output format to enable C++11 interfaces

### ISSUE THREAD

**Issue by bradking** [CastXML/CastXML#72]
CastXML's current goal is only to reproduce [gccxml](https://github.com/gccxml/gccxml)'s output format for C++98 interfaces for use with projects such as [pygccxml](https://github.com/gccxml/pygccxml).  This is why the output generation is activated by the `--castxml-gccxml` option.  The naming leaves room for other output-activation options to be added later that produce alternative output formats.  However, actually adding such formats is not currently a goal.

This issue serves as a placeholder for all issues submitted that request addition of information to the output format that is not produced by gccxml.  Addition of such information will not match gccxml output and therefore cannot be included with the `--castxml-gccxml` option.  Instead an alternative output format needs to be designed, activated by a new `--castxml-output` option, implemented, and added to the test suite.  Currently adding such an option is not an upstream goal.

**Comment by iMichka** [comment]
@bradking Great thing you opened that ticket as placeholder.

I would be pleased to support the new format in pygccxml, as soon as new things are added to CastXML. But I won't be able to actively work on CastXML and push things forward for the moment.

**Comment by bradking** [comment]
I think the first step here is just to add a `--castxml-output=$v` option, where `$v` will be a format major version number.  For now it can be required to be just `1`.  This will allow future major format transitions.

The only differences in the format initially should be the top-level element.  Instead of `GCC_XML` it should be `CastXML`.  Also we should consider a new version scheme to be spelled out in its attributes.

The test suite should the be updated to cover the new format for all of the existing tests while preserving the existing `gccxml`-format tests too.

Once all that is in place we can start adding things to the new format while increasing its minor version number.

**Comment by bradking** [comment]
Resolved by #78.
