### ISSUE TITLE
Test  #75: cmd.cc-msvc-builtin-1900 fails on armel and mips64el 

### ISSUE THREAD

**Issue by gerddie** [CastXML/CastXML#73]
The test 75 fails on Debian armel and mips64el, see the the build logs for: [armel](https://buildd.debian.org/status/fetch.php?pkg=castxml&arch=armel&ver=0.1%2Bgit20160706-1&stamp=1467822344) and [mips64el](https://buildd.debian.org/status/fetch.php?pkg=castxml&arch=mips64el&ver=0.1%2Bgit20160706-1&stamp=1467822300). 

The error refers to the version from the 2016-07-06.

Output: 
      result does not match that expected.
      stderr does not match that expected.

     Command was:

     command> "/«BUILDDIR»/castxml-0.1+git20160706/obj-arm-linux-gnueabi/bin/castxml" "--castxml-cc-msvc" "(" "/«BUILDDIR»/castxml-0.1+git20160706/obj-arm-linux-gnueabi/test/cc-msvc" "-msc=1900" ")" "/«BUILDDIR»/castxml-0.1+git20160706/test/input/make_integer_seq.cxx"

    Expected result to match:
      expect-result> 0
    Expected stderr to match:
     expect-stderr> ^$

    Actual result:
     actual-result> 1

    Actual stdout:
     actual-stdout> 

    Actual stderr:

     actual-stderr> /«BUILDDIR»/castxml-0.1+git20160706/test/input/make_integer_seq.cxx:2:9: error: unknown type name '__make_integer_seq'
     actual-stderr> typedef __make_integer_seq<seq, int, 3> seq_A;
     actual-stderr>         ^
     actual-stderr> /«BUILDDIR»/castxml-0.1+git20160706/test/input/make_integer_seq.cxx:2:27: error: expected unqualified-id
     actual-stderr> typedef __make_integer_seq<seq, int, 3> seq_A;
     actual-stderr>                           ^
     actual-stderr> /«BUILDDIR»/castxml-0.1+git20160706/test/input/make_integer_seq.cxx:6:13: error: use of undeclared identifier 'seq_A'
     actual-stderr> assert_same<seq_A,seq_B> enforce;
     actual-stderr>             ^
     actual-stderr> 3 errors generated.

**Comment by bradking** [comment]
Thanks.  What version of LLVM/Clang is this built against?

**Comment by gerddie** [comment]
Version 3.8.

**Comment by bradking** [comment]
The test in question was added by commit f1bb3c2ac4ff530b38ce0cc627f04d47b21d76f2.  The implementation of support for `__make_integer_seq` varies depending on the version of LLVM/Clang.  With LLVM/Clang 3.8 and above we assume that it is provided already.  Perhaps it is arch-dependent?

Or, might the LLVM/Clang for the architectures in question have been built from a pre-release 3.8 version (that does not provide this builtin)?

**Comment by gerddie** [comment]
The used version was indeed a pre-release: 1:3.8~svn247576-1, and on the other archs at first try clang-3.8-dev was uninstallable, and later it was the release version. 

I'll ask for a give-back of the builds and if they succeed I'll close this bug.

**Comment by gerddie** [comment]
Unfortunately, clang-3.8.1 [FTBFS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820535) on armel currently, so this may take some time.

**Comment by bradking** [comment]
As a last resort you could patch the build of CastXML for these archs.  Hack the preprocessor condition added in the commit I linked previously to use CastXML's simulated support for `__make_integer_seq` instead of using LLVM/Clang's builtin support.

**Comment by gerddie** [comment]
Great idea, since Debian is otherwise already on 3.8.1 I can use LLVM_VERSION_PATCH < 1 for the test.

**Comment by gerddie** [comment]
It worked, thanks.
