### ISSUE TITLE
cannot parse <string> with -std=c++14

### ISSUE THREAD

**Issue by 4picht** [CastXML/CastXML#76]
Hi,

I have a problem parsing some files without a start position:

test.cpp:
`#include <string>`

> castxml -std=c++14 test.cpp --castxml-gccxml -o test.xml
> castxml: /usr/local/include/clang/AST/Decl.h:238: llvm::StringRef clang::NamedDecl::getName() const: Assertion `Name.isIdentifier() && "Name is not a simple identifier"' failed.

gdb tells me, this is Output.cxx line 1854

It happens in line 5555 of `/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/basic_string.h`

which reads
`operator""s(const char* __str, size_t __len)`

in context:

	  inline namespace literals
	  {
	  inline namespace string_literals
	  {
	
	    _GLIBCXX_DEFAULT_ABI_TAG
	    inline basic_string<char>
	    operator""s(const char* __str, size_t __len)
	    { return basic_string<char>{__str, __len}; }
	
	#ifdef _GLIBCXX_USE_WCHAR_T
	    _GLIBCXX_DEFAULT_ABI_TAG
	    inline basic_string<wchar_t>
	    operator""s(const wchar_t* __str, size_t __len)
	    { return basic_string<wchar_t>{__str, __len}; }
	#endif
	
	#ifdef _GLIBCXX_USE_C99_STDINT_TR1
	    _GLIBCXX_DEFAULT_ABI_TAG
	    inline basic_string<char16_t>
	    operator""s(const char16_t* __str, size_t __len)
	    { return basic_string<char16_t>{__str, __len}; }
	
	    _GLIBCXX_DEFAULT_ABI_TAG
	    inline basic_string<char32_t>
	    operator""s(const char32_t* __str, size_t __len)
	    { return basic_string<char32_t>{__str, __len}; }
	#endif
	
	  } // inline namespace string_literals
	  } // inline namespace literals

I tried to find a way to tell from the clang::FunctionDecl that it is a custom literal operator, but I did not really manage, the clang documentation is ... rather extensive but not really useful for someone not too familiar with it. It took me over an hour to even wrangle a useful representation of the input source code location from the source manager.

It would be really great if you could implement this language feature or just skip these function declarations.

Thanks!

**Comment by bradking** [comment]
This looks a lot like #62 which was fixed by commit d5934bd08651dbda95a65ccadcc5f39637d7bc59.

**Comment by 4picht** [comment]
Yes, a similar change in Output.cxx does remove the error message but also removes the output for the function.

**Comment by bradking** [comment]
I'm able to reproduce this using the input

```c++
namespace start {
  unsigned long long operator""_u(unsigned long long);
}
```

CastXML documents that the `--output-gccxml` output format excludes non-C++98 constructs, so we should simply exclude user defined literal operators.  Fix forthcoming.
