### ISSUE TITLE
gccxml incompatibilities

### ISSUE THREAD

**Issue by sstjohn** [CastXML/CastXML#80]
CastXML's gccxml-compatible output seems to leave off the 'size' and 'align' attributes for some types, eg:

<pre>
$ cat pointer.h
typedef void *pointer;
$ gccxml -fxml-start=pointer -fxml=pointer_g.xml -std=c89 pointer.h
$ cat pointer_g.xml | grep PointerType
   &lt;PointerType id="_1" type="_3" <b>size="64" align="64"</b>/&gt;
$ castxml --castxml-gccxml --castxml-start pointer -o pointer_c.xml -std=c89 pointer.h
$ cat pointer_c.xml | grep PointerType
   &lt;PointerType id="_2" type="_4"/&gt;
</pre>

Same thing with enums.

**Comment by sstjohn** [comment]
Also, ``Union`` and ```Struct``` tags aren't getting the mangling attributes set:

<pre>
$ cat utest.h
union utest { 
	int as_signed;
	unsigned as_unsigned;
};
$ gccxml -fxml-start=utest -fxml=utest_g.xml -std=c89 utest.h
$ cat utest_g.xml | grep Union
  &lt;Union id="_1" name="utest" context="_2" <b>mangled="5utest" demangled="utest"</b> location="f0:1" file="f0" line="1" artificial="1" size="32" align="32" members="_3 _4 _5 _6 _7 _8 " bases=""&gt;
$ castxml --castxml-gccxml --castxml-start utest -o utest_c.xml -std=c89 utest.h
$ cat utest_c.xml | grep Union
  &lt;Union id="_1" name="utest" context="_2" location="f1:1" file="f1" line="1" members="_3 _4" size="32" align="32"/&gt;
</pre>

**Comment by bradking** [comment]
Thanks!

The lack of size/align on `PointerType` is certainly a bug.

The lack of `mangled` on a type like `Union` is not a bug because they don't have any corresponding symbols to be mangled.  It was a bug in gccxml that it ever had these fields.

**Comment by sstjohn** [comment]
Hey, thanks. &lt;Enumeration&gt;'s would like a similar fix, it seems:

```
$ cat enumeration.h
enum enumeration {
	first = 1,
	second,
	third
};
$ gccxml -fxml-start=enumeration -fxml=enumeration_g.xml enumeration.h && castxml --castxml-gccxml --castxml-start enumeration -o enumeration_c.xml enumeration.h
$ cat enumeration_g.xml enumeration_c.xml | grep \<Enumeration
  <Enumeration id="_1" name="enumeration" context="_2" location="f0:1" file="f0" line="1" artificial="1" size="32" align="32">
  <Enumeration id="_1" name="enumeration" context="_2" location="f1:1" file="f1" line="1">
```

**Comment by sstjohn** [comment]
Thanks for the response. I can confirm the size/align fixes for Enumerations and PointerTypes. 

I'd like to revisit the ```mangled``` attributes issue for a sec, which turns out to actually be an issue with a lack of ```name``` attribute as well. These are all issues I've been running into using xml2py from ctypeslib on CastXML --castxml-gccxml output.

Consider:

```
$ cat sus.h
struct sus {
	union {
		struct {
			int first_half :16;
			int second_half :16;
		};
		int all_of_it;
	};
};
$ gccxml -fxml-start=sus -fxml=sus_g.xml -std=c89 sus.h && castxml --castxml-gccxml --castxml-start sus -o sus_c.xml -std=c89 sus.h
$ xml2py sus_g.xml -o sus_g.py && xml2py sus_c.xml -o sus_c.py
Traceback (most recent call last):
  File "/usr/bin/xml2py", line 6, in <module>
    sys.exit(main())
  File "/usr/lib/pymodules/python2.7/ctypeslib/xml2py.py", line 199, in main
    types=options.kind)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/codegenerator.py", line 834, in generate_code
    items = parse(xmlfile)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 423, in parse
    parser.parse(xmlfile)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 57, in parse
    self.startElement(node.tag, dict(node.items()))
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 70, in startElement
    result = mth(attrs)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 307, in Union
    name = MAKE_NAME(attrs["mangled"])
KeyError: 'mangled'
$ cat sus_g.xml sus_c.xml | grep Union
  <Union id="_4" context="_1" access="public" mangled="N3sus3._0E" demangled="sus::._0" location="f0:2" file="f0" line="2" artificial="1" size="32" align="32" members="_9 _10 _11 " bases=""/>
  <Union id="_3" context="_1" location="f1:2" file="f1" line="2" members="_8 _9 _10 _11 _12" size="32" align="32"/>
$
```

The ctypeslib code at issue reads as follows: 
```python
    def Union(self, attrs):
        name = attrs.get("name")
        if name is None:
            name = MAKE_NAME(attrs["mangled"])
        bases = attrs.get("bases", "").split()
        members = attrs.get("members", "").split()
        align = attrs["align"]
        size = attrs.get("size")
        return typedesc.Union(name, align, members, bases, size)
```

... which fails at line three for in this example, as neither the 'name' nor 'mangled' attributes are being set by castxml on the ```<Union>```, resulting in incompatibility with gccxml.

(I can make this a new issue ticket if that'd be more convenient.)

**Comment by bradking** [comment]
@sstjohn please open a new issue for the `Union` problem.  Thanks!
