### ISSUE TITLE
gccxml/castxml incompatibility on anonymous, nested unions and structs

### ISSUE THREAD

**Issue by sstjohn** [CastXML/CastXML#84]
There appears to be an incompatibility between ```gccxml``` and ```castxml --castxml-gccxml``` when processing nested/anonymous structs and unions, in that there are circumstances when castxml's results lack the ```name``` or ```mangled``` attributes that gccxml would have produced. This is an issue I've been running into using xml2py from ctypeslib on CastXML --castxml-gccxml output.

Consider:

```
$ cat sus.h
struct sus {
	union {
		struct {
			int first_half :16;
			int second_half :16;
		};
		int all_of_it;
	};
};
$ gccxml -fxml-start=sus -fxml=sus_g.xml sus.h && castxml --castxml-gccxml --castxml-start sus -o sus_c.xml sus.h
$ xml2py sus_g.xml -o sus_g.py && xml2py sus_c.xml -o sus_c.py
Traceback (most recent call last):
  File "/usr/bin/xml2py", line 6, in <module>
    sys.exit(main())
  File "/usr/lib/pymodules/python2.7/ctypeslib/xml2py.py", line 199, in main
    types=options.kind)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/codegenerator.py", line 834, in generate_code
    items = parse(xmlfile)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 423, in parse
    parser.parse(xmlfile)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 57, in parse
    self.startElement(node.tag, dict(node.items()))
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 70, in startElement
    result = mth(attrs)
  File "/usr/lib/pymodules/python2.7/ctypeslib/codegen/gccxmlparser.py", line 307, in Union
    name = MAKE_NAME(attrs["mangled"])
KeyError: 'mangled'
$ cat sus_g.xml sus_c.xml | grep Union
  <Union id="_4" context="_1" access="public" mangled="N3sus3._0E" demangled="sus::._0" location="f0:2" file="f0" line="2" artificial="1" size="32" align="32" members="_9 _10 _11 " bases=""/>
  <Union id="_3" context="_1" location="f1:2" file="f1" line="2" members="_8 _9 _10 _11 _12" size="32" align="32"/>
```

The ctypeslib code at issue reads as follows:
```python
    def Union(self, attrs):
        name = attrs.get("name")
        if name is None:
            name = MAKE_NAME(attrs["mangled"])
        bases = attrs.get("bases", "").split()
        members = attrs.get("members", "").split()
        align = attrs["align"]
        size = attrs.get("size")
        return typedesc.Union(name, align, members, bases, size)
```
... which fails at line three for in this example, as neither the 'name' nor 'mangled' attributes are being set by castxml on the ```<Union>```, resulting in incompatibility with gccxml.

(This issue has been split off from #80: gccxml incompatibilites.)

**Comment by bradking** [comment]
Cc: @iMichka 

CastXML's goal for the `--castxml-gccxml` output format is to be close to the gccxml format and easy to port clients, but not *exactly* the same.  We fix bugs that gccxml had.  Clients should be ported accordingly, just as if the bugs had been fixed in gccxml originally.

The example shown is an anonymous union and so has no `name=`.  Types in general should not have `mangled=` or `demangled=` because they have no corresponding symbols.  Only functions, methods, variables, etc. have symbols and so only those should have these attributes.

**Comment by sstjohn** [comment]
I guess I just don't understand the purpose of a backwards-compatibility mode that isn't actually backwards compatible. My purpose here is to use CastXML as a replacement in a build process that's currently working with gccxml (bugs and all), as the Debian and Ubuntu maintainers have suggested through their packaging choices. The next step in my build process is to use xml2py from ctypeslib to write Python wrappers from the gccxml'd header files. Since I don't really want to rewrite xml2py, I guess I'll just have to preprocess CastXML's output?

Incidentally, ```castxml --castxml-gccxml``` does indeed sometimes produce a name tag for anonymous unions:

```$ cat au.h
typedef union {
	int first;
	int second;
} au;
$ castxml --castxml-gccxml -o - au.h | grep Union
  <Union id="_6" name="" context="_1" location="f1:1" file="f1" line="1" members="_12 _13" size="32" align="32"/>
```

**Comment by iMichka** [comment]
@bradking Thanks for letting me know. I do not remember all the details but I think anonymous unions are already supported in the newer versions of pygccxml since some time now. It did bite us at some point, but it was easy to fix on my side. I'll double-check later just to be sure.

**Comment by sstjohn** [comment]
Oh lol wait, does ```pygccxml```:```xml2py```::```castxml```:```gccxml``` for this use case?

**Comment by bradking** [comment]
> a backwards-compatibility mode that isn't actually backwards compatible

It isn't a strict compatibility mode and isn't documented as such.  The goal was only to make porting gccxml clients simple, but not necessarily zero work.  If gccxml had continued to be developed it may have fixed the same bugs and then clients would have to be updated anyway.  Instead CastXML has taken over that development path.

> ctypeslib code at issue reads as follows:

In this case it looks like `ctypeslib` that needs updating.  The quoted code can have just a couple lines changed to tolerate missing attributes and provide defaults.

**Comment by sstjohn** [comment]
You're right, CastXML is documented as "the successor to gccxml," and ```--castxml-gccxml``` is documented as producing "XML output in a format close to that of gccxml," (but not a version of `gccxml` that ever existed.) That `--castxml-gccxml` produces "backwards-compatible" output is very strongly implied, but not explicitly stated.

That's all semantics, though. You're changing an output format that's been stable for half-a-dozen years-- please keep in mind that `gccxml` is now but a script that wraps `castxml --castxml-gccxml` in modern Ubuntu. Since the only standard that has ever existed for "the gccxml output format" is `gccxml` itself, and you're not writing to a DTD, how can anyone safely consume the output of this functionality?

**Comment by bradking** [comment]
> how can anyone safely consume the output of this functionality?

Update clients accordingly.  If the gccxml package had been updated with such a bug fix the same thing would have been needed.  In some sense such an update was done by distro packagers that use the wrapper script.

We've gone to great lengths to make CastXML's `--castxml-gccxml` output close to that of gccxml's, including some non-trivial internal gymnastics.  Without this clients would have needed total rewrites instead of minor tweaks and distros would have been left unable to provide an updated `gccxml` package at all.  A line has to be drawn somewhere short of perfect bug-for-bug compatibility, and someone may always come along on the other side of that line no matter how far we push it.

The `pygccxml` client has been updated.  Other clients have been updated.  `ctypeslib` should be updated too.

**Comment by sstjohn** [comment]
Is the format, or the changes you have made thereto, documented *anywhere*?

**Comment by sstjohn** [comment]
The ```python-ctypeslib``` incompatibility is now documented at https://bugs.launchpad.net/ubuntu/+source/python-ctypeslib/+bug/1657234.

**Comment by bradking** [comment]
> Is the format, or the changes you have made thereto, documented anywhere?

Unfortunately no.  It was never documented by gccxml either.  I've opened #85 for that.

**Comment by sajjadafridi** [comment]
My question is pretty simple but still, i want to know that the data type in the XML output format is mapped in the form of the number. Is there a way to check which datatype is associated with the number? 

Thanks
