### ISSUE TITLE
Document output formats

### ISSUE THREAD

**Issue by bradking** [CastXML/CastXML#85]
CastXML supports both the `--castxml-gccxml` and the new/experimental `--castxml-output=1` options for output.  The gccxml output format was never formally documented.  CastXML's FAQ currently says there is no DTD or schema.  The lack of documentation makes clients parsing the format harder to write and maintain.

**Comment by loopless** [comment]
I would strongly agree with the sentiment of this comment. The lack of an XSD schema for CastXML output is a real barrier to writing parsers as well as just being able to understand/document the format.

**Comment by Smattr** [comment]
Does this mean you would accept contributions of an XSD or RNG? Or is the choice of no schema deliberate to allow arbitrary changes to the output format in future?

**Comment by bradking** [comment]
@Smattr I'd love to see a proper schema contributed for the format generated by `--castxml-output=1`.  It would also strengthen our test suite to verify each case's output against the schema.

**Comment by nnemkin** [comment]
I've created a schema for CastXML output: https://gist.github.com/nnemkin/13d293b2ffbfe5a8eb0bee8972d2617a.
Both `--castxml-output=1` and `--castxml-gccxml` are supported, they are almost the same as far as the schema is concerned.
It passes CastXML test suite (using the `--schema` parameter to `xmllint`).

**Comment by bradking** [comment]
@nnemkin thanks!  Can you look at integrating that into the documentation and the test suite through a PR?  It can be mentioned from the docs the same way as [this code](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.19.1/Help/manual/cmake-presets.7.rst#L364-368) links it for CMake's presets format.
