### ISSUE TITLE
Missing "name" attribute in Converter tag

### ISSUE THREAD

**Issue by todoooo** [CastXML/CastXML#86]
I'm running into an error with CableSwig when building from CastXML output containing "Converter" tags, because there is no "name" attribute in the XML.

>CUSTOMBUILD : error : In ..\CableSwig\Cable\Parsers\cableXMLSourceParser.cxx, line 584
>XMLSourceParser (000001B62D6B7100): No name on Named object Converter

Here's an example of output produced by both gccxml and castxml. 

c:\>cat example.cxx
class start
{
  virtual int method(int) = 0;
  virtual operator int() = 0;
  virtual ~start() = 0;
};

c:\>gccxml -fxml=gcc-example.xml  example.cxx
c:\>cat gcc-example.xml | grep Converter
`<Converter id="_10" demangled="start::operator int()" mangled="_ZN5startcviEv" name="operator 1" context="_4" line="4" file="f0" location="f0:4" extern="1" access="private" returns="_16" pure_virtual="1" virtual="1"/>`

c:\>castxml --castxml-gccxml -o -cast-example.xml  example.cxx
c:\>cat cast-example.xml | grep Converter
`<Converter id="_7" line="4" file="f1" location="f1:4" context="_3" mangled="_ZN5startcviEv" returns="_16" attributes="__thiscall__" pure_virtual="1" virtual="1" access="private"/>`

I deduce this is due to the empty string being passed to OutputFunctionHelper() below. I'm not sure if the "extern" attribute should also be there.

```
void ASTVisitor::OutputCXXConversionDecl(clang::CXXConversionDecl const* d,
                                         DumpNode const* dn)
{
  if (d->getDescribedFunctionTemplate()) {
    // We do not implement function template output yet.
    this->ASTVisitorBase::OutputCXXConversionDecl(d, dn);
    return;
  }

  unsigned int flags = FH_Returns;
  if (d->isConst()) {
    flags |= FH_Const;
  }
  if (d->isVirtual()) {
    flags |= FH_Virtual;
  }
  if (d->isPure()) {
    flags |= FH_Pure;
  }
  this->OutputFunctionHelper(d, dn, "Converter", "", flags);
}
```

**Comment by bradking** [comment]
> `name="operator 1"`

This output by gccxml was a bug.  The operator has no name.  CastXML is correctly not producing the attribute.  Our documented goal for `--castxml-gccxml` is to produce output that is close to that of gccxml, but not identical.  That makes it easy to port clients, but is not 100% bug-for-bug compatible.

The `CableSwig` parser would need to be fixed for this, though AFAIK that project hasn't been used or maintained in years.  ITK (its original purpose) no longer uses it, and now uses pygccxml instead.  `pygccxml` is maintained and actively updated for use with CastXML.

**Comment by todoooo** [comment]
@Brad.
I can patch the CableSwig source and create a pull request, but it will probably never be committed to the master branch, if it is no longer being maintained. I was hoping for a solution in your active project. 

I don't understand your assertion that having a "name" attribute in the Converter element is a bug? Surely passing "operator" to OutputFunctionHelper() would only serve to clarify the intent of the XML element. So how does this negatively impact CastXML

**Comment by bradking** [comment]
The Converter doesn't have a name.  This is evidenced by the fact that GCCXML's output made up some name (that AFAIK came from GCC internal implementation details).  There is no syntax for a human author to provide one.  It doesn't make sense to have the field.  We're not going to add a non-sensical field with a bogus value just to work around a limitation of an unmaintained tool.

If you're worried about making local fixes to CableSwig because it is unmaintained (it hasn't had a commit since 2012) then perhaps it is not a good choice to use.  Alternatively you could extract the Cable parser part of its source and start a new project based on it.
