### ISSUE TITLE
Type aliases, auto return types, and lambda types not handled

### ISSUE THREAD

**Issue by todoooo** [CastXML/CastXML#89]
I'm trying to build the Kitware mummy library using castxml and VS 2017

During the build process I'm getting an unknown attribute type in the XML output and I cannot figure out why. Furthermore I cannot reproduce the error with a simple cxx file. The problem occurs with ReferenceType id="_101" in the attached file.

The code segment which causes the problem is 
349--->	mapped_type& operator[](const key_type& _Keyval)
		{	// find element matching _Keyval or insert with default mapped
		return (try_emplace(_Keyval).first->second);
		}

Does CastXML have a problem with const reference types as method parameters?

**Comment by bradking** [comment]
> The problem occurs...in the attached file.

@todoooo please attach the file.

Also, how did you obtain or build CastXML?  What it the output of `castxml --version`?

**Comment by todoooo** [comment]
I used the CastXMLsuperbuild to build LLVM and then checked out the latest master branch of CastXML.
castxml version 0.1-gfab9c47
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-pc-windows-msvc
Thread model: posix

**Comment by bradking** [comment]
@todoooo thanks.  VS 2017's C++ standard library started using type aliases (`using a = b`) in place of typedefs (`typedef b a`).  Please try the fix in e51382fbcccc390a25d90f2103838c6e979e7e30.

**Comment by todoooo** [comment]
@bradking 
Thanks. Much appreciated. That got me a bit further. I haven't built mummy for a few months and I updated the MSVC source in the meantime, so I figured MS had changed something. 

I'm now running into another problem with an unimplemented element, although I might just have to patch mummy to ignore this. Please see type _464 in the attached xml.
[Oops.zip](https://github.com/CastXML/CastXML/files/1338846/Oops.zip)

BTW I also noticed a small difference between CastXML and GCCXML output on reference type elements. It's a one liner change, that you might, or might not, want to incorporate into CastXML. Here's the patch.
![untitled](https://user-images.githubusercontent.com/15134761/30940539-e235c61a-a43d-11e7-9fc3-ef94ff0845b9.png)

**Comment by bradking** [comment]
Please see commit bbe3117a26ad11ba74a8f2c3f0a38bf3ef9864bb for a fix for `auto` return types on functions.

I'll take a look at the lvalue reference abi attributes.

**Comment by todoooo** [comment]
Hi Brad
Thanks for the updates.

I've hit another problem now with a missing name attribute for some Constructor & Destructor elements. In fact you can see this in the Oops.xml file, attached previously, for ids _360, _361 and others. Perhaps the name attribute should be "anonymous" in these cases.

**Comment by bradking** [comment]
Please see commit a80084fb43452746b52e33bdf2460f9cec3c274b for a fix for types generated for lambdas.

**Comment by todoooo** [comment]
Fantastic Brad! 

After your latest fix I was able to track down the last bug in my changes for Mummy and then build and run all the tests using castXML. Now I need to send a pull request to the Mummy team at Kitware, if they still exist, once I have tweaked the CMake files slightly to avoid a breaking change for those silly enough to persist with gccxml. Whereas gccxml had to patch the MSVC source code on the fly in order to work, that's not necessary with castXML. Maybe the ITK team will be keen to ditch pygccxml now.   :grin:

Here's the minor patch I made on my machine to tweak the castXML output. I know you don't want to include this, but it saved me having to touch CableSWIG, which Mummy depends on.
![untitled](https://user-images.githubusercontent.com/15134761/31042702-621860fe-a60a-11e7-962d-34b3bd803b52.png)

**Comment by bradking** [comment]
Great, thanks for trying all this out.

**Comment by bradking** [comment]
> I need to send a pull request to the Mummy team at Kitware

What repo URL did you clone to get mummy?

> Maybe the ITK team will be keen to ditch pygccxml now

pygccxml has been maintained and updated to support CastXML.

**Comment by todoooo** [comment]
> What repo URL did you clone to get mummy?

git://public.kitware.com/mummy.git

**Comment by todoooo** [comment]
Hi Brad

I've come across another issue building Activiz. For the following class, gccxml produces a "destructor" element with a name attribute, name="$_0", for the union, but the destructor element generated by CastXML does not have a name attribute.

`class start
{
  union
  {
    float Float;
  } Data;
};` 

Is this another case where no constructor/destructor element should be produced like the lambda functions? Or should I just patch Mummy to ignore nameless destructors?

**Comment by bradking** [comment]
I'll take a look at fixing the destructor names.

**Comment by bradking** [comment]
See commit ae62b1a29c8233c3dd40fc3e293ddcdbe0bdcccc for a fix to the anonymous union destructor names.

**Comment by todoooo** [comment]
Thanks Brad. 

I should mention that I'm using the --gccxml option with castxml for both Mummy and Activiz, so it can be utilised to handle issues peculiar to those projects, if necessary.   :)

Todd
