### ISSUE TITLE
problem with function returning reference

### ISSUE THREAD

**Issue by heneault** [CastXML/CastXML#9]
In compatibility mode (gccxml), castxml differ in behavior for function returning a typedef reference. The following test case https://gist.github.com/heneault/558f3f18a07e0ddf608e#file-test_ref_return shows the issue. The output from the original gccxml is there https://gist.github.com/heneault/1bdb190a85c9f26f65c2#file-test_ref_gccxml-xml . The return type for the method fcn is a reference type, which itself link to the fundamental type.
The output from castxml is there:
https://gist.github.com/heneault/07a4cdd57a4b3b3e1bb5#file-test_ref_castxml-xml
In that case, the return of the fcn is a typedef that link to the reference type. This extra redirection break the compatibility of tools like genreflex.

**Comment by bradking** [comment]
The `--castxml-gccxml` option is documented as "produces a format *close* to that of gccxml".  It is not intended to produce absolutely identical output.  The lack of the typedef here was tolerated as a limitation of gccxml, but castxml has the information.  There are many such cases.  Tools consuming this output should simply be fixed to understand what CastXML produces.

In short: `--castxml-gccxml` is intended to make porting tools easy, but not zero work.
