### ISSUE TITLE
enumerated type inside a struct

### ISSUE THREAD

**Issue by todoooo** [CastXML/CastXML#91]
I'm looking at this definition in VTK8 and wondering if CLang produces a type modifier such as "internal" which could be output in XML indicating that the enumeration doesn't exist outside the struct. This might also apply to internal classes.
```
struct vtkTimerLogEntry
{
  enum LogEntryType
  {
    INVALID = -1,
    STANDALONE,    // an individual, marked event
    START,         // start of a timed event
    END,           // end of a timed event
    INSERTED       // externally timed value
  };
  double WallTime;
  int CpuTicks;
  std::string Event;
  LogEntryType Type;
  unsigned char Indent;
  vtkTimerLogEntry() : WallTime(0), CpuTicks(0), Type(INVALID), Indent(0)
    {}
};
```
In the particular case where Mummy wraps only descendants of vtkObject and other basic types (including enumerated types, but not structs or unions) it attempts to wrap vtkTimerLogEntry::LogEntryType as a valid type, which it is not because vtkTimerLogEntry is not wrapped.

**Comment by bradking** [comment]
Cc: @dlrdave

The `context=""` attribute of the enumeration type should point at the struct rather than a namespace.  This is how to distinguish this case.

**Comment by todoooo** [comment]
Thanks.
