### ISSUE TITLE
Adding support to C++11 scoped enumerations

### ISSUE THREAD

**Issue by RomanYakovenko** [CastXML/CastXML#94]
Hello. CastXML does not support C++11 scoped enumerations. 
The attached patch adds supports for those enums. [scoped-enums.patch.txt](https://github.com/CastXML/CastXML/files/1439251/scoped-enums.patch.txt)

Thanks to clang documentation, it was very easy to add it to Output.cxx file (
https://clang.llvm.org/doxygen/classclang_1_1EnumDecl.html - look for isScoped), but I didn't managed to run & pass the tests. The generated files were empty. 

Your help on this issue is appreciated.  

Regards,
Roman

**Comment by bradking** [comment]
Thanks.  For reference, the non-test part of the proposed patch is:

```patch
diff --git a/src/Output.cxx b/src/Output.cxx
index e67fcd3..fd885bd 100644
--- a/src/Output.cxx
+++ b/src/Output.cxx
@@ -1873,6 +1873,9 @@ void ASTVisitor::OutputEnumDecl(clang::EnumDecl const* d, DumpNode const* dn)
   this->PrintLocationAttribute(d);
   this->PrintABIAttributes(d);
   this->PrintAttributesAttribute(d);
+  if( d->isScoped() ){
+      this->OS << " is_scoped=\"1\"";
+  }
   clang::EnumDecl::enumerator_iterator enum_begin = d->enumerator_begin();
   clang::EnumDecl::enumerator_iterator enum_end = d->enumerator_end();
   if (enum_begin != enum_end) {
```

This will be a good addition to the castxml output format, but maybe not for the gccxml variant.  gccxml never had this value or supported C++11.  I'll look closer when I get a chance.

**Comment by hjmjohnson** [comment]
@bradking @thewtex 

I think this may be related to the failures in https://github.com/InsightSoftwareConsortium/ITK/pull/1061

in particular:  https://open.cdash.org/viewBuildError.php?type=1&buildid=6049412
