### ISSUE TITLE
c++ magic

### ISSUE THREAD

**Issue by todoooo** [CastXML/CastXML#97]
Hi Brad

Looking through the source code for CastXML I'm completely stumped about how the node map, DeclNodes, in the PrinterHelper class is populated.
```
  // Map from clang AST declaration node to our dump status node.
  typedef std::map<clang::Decl const*, DumpNode> DeclNodesMap;
  DeclNodesMap DeclNodes;
```
It is passed to clang somewhere? Could you enlighten me please?

**Comment by bradking** [comment]
Calls to `GetDumpNode`:

```c++
  /** Get the dump status node for a Clang declaration.  */
  DumpNode* GetDumpNode(clang::Decl const* d) { return &this->DeclNodes[d]; }
```

populate it.  The `std::map`'s `operator[]` inserts default-constructed entries when indexing a previously-unseen key.

**Comment by todoooo** [comment]
Thanks. It's so obvious now. :)
