### ISSUE TITLE
Missing `__has_unique_object_representations` breaks castxml run on debian sid when using -std=c++17

### ISSUE THREAD

**Issue by textshell** [CastXML/CastXML#98]
The on debian sid (which uses gcc 7.2 plus backported patches) (using the binary clang 5 from llvm.org) the following fails:

    ./obj-x86_64-linux-gnu/bin/castxml --castxml-cc-gnu '(' g++ -std=c++17 ')' ~/test.cpp -std=c++17

With test.cpp:

    #include <type_traits>

The error is caused by code in `type_traits` that sees `__GNUC__` is set to 7 (because of --castxml-cc-gnu) and blindly assumes the builtin `__has_unique_object_representations` is available. But this is only supported in clang trunk (likely will be in 6.0) (https://bugs.llvm.org/show_bug.cgi?id=34942).

My current workaround is using the following patch. But i'm not sure if this is the right way at all.
```
diff --git a/src/RunClang.cxx b/src/RunClang.cxx
index de8f25a..5bc318c 100644
--- a/src/RunClang.cxx
+++ b/src/RunClang.cxx
@@ -250,6 +250,15 @@ protected:
                     "#define __builtin_va_arg_pack_len() 1\n";
       }
 
+
+#if LLVM_VERSION_MAJOR < 6
+      // Clang 6 and above provide a __has_unique_object_representations builtin needed
+      // in C++17 mode.  Provide it ourselves for older Clang versions.
+
+      builtins += "\n"
+                  "#define __has_unique_object_representations(x) 0\n";
+#endif
+
       // Provide __float128 if simulating the actual GNU compiler.
       if (!this->HaveFloat128(CI) &&
           this->NeedFloat128(this->Opts.Predefines)) {
```

**Comment by bradking** [comment]
Thanks for the detailed investigation and report!  It should be fixed now.

**Comment by textshell** [comment]
Thanks.
I will test this version tomorrow when i'm at the office again.
I noticed your commit only enables this for gcc, but it seems msvc intends to use this builtin too (after all it was reported by MS's STL-Maintainer), although i do not have a msvc testcase.

**Comment by bradking** [comment]
If MSVC headers start using the builtin we can look at defining it more generally.

Since the definition is only syntactic and doesn't actually work, supporting real code using this builtin will require building CastXML against a Clang that provides the real builtin.

**Comment by textshell** [comment]
I've confirmed this fix works for my use-case. Thanks again.
